"""Astra's 73 animations -> the app's mascot sheet + frame index.

Reads scripts/mascot/v2/astra/<anim>/NNN.png (64x64, 4 colours + transparent) and
manifest.json (durations_ms). Writes, next to the renderer:
  frontend-react/src/components/chat/mascot/sheet.png   every drawn frame, 16 per row
  frontend-react/src/components/chat/mascot/frames.ts   MascotState, VARIANTS (sheet indices)
Durations become repeated indices at the renderer's fixed tick (FRAME_MS = 160):
500 ms -> 3 ticks, 167 -> 1. Run from the repo root: python scripts/mascot/v2/to_frames_ts.py
"""
import glob, json, os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
SRC = os.path.join(ROOT, 'scripts', 'mascot', 'v2', 'astra')
DST = os.path.join(ROOT, 'frontend-react', 'src', 'components', 'chat', 'mascot')
FRAME_MS = 160
N = 64
COLS = 16

# App state -> the animations it may play (the renderer picks one variant per state
# change, as before). The first entry is the canonical one (FRAMES[state]).
VARIANTS = {
    'idle':       ['idle', 'idle-look-around', 'idle-scratch', 'idle-yawn', 'idle-sit'],
    'typing':     ['typing'],
    'thinking':   ['thinking', 'thinking-deep', 'thinking-scratch-head', 'planning', 'remembering', 'deciding'],
    'calling':    ['calling', 'calling-phone', 'receiving-message', 'sending-file'],
    'done':       ['done', 'done-nod', 'tests-green'],
    'running':    ['running-shell', 'committing', 'installing-skill', 'downloading'],
    'wave':       ['wave', 'goodbye'],
    'sleep':      ['sleep', 'dreaming'],
    'surprised':  ['surprised', 'drag-drop'],
    'curious':    ['idle-look-around', 'listening'],
    'celebrate':  ['celebrate', 'excited'],
    'reading':    ['reading', 'reading-pdf', 'reading-attachment', 'browsing', 'paste'],
    'searching':  ['searching', 'searching-deep', 'fetching-url'],
    'building':   ['building', 'testing'],
    'writing':    ['writing', 'writing-code', 'image-generating', 'exporting'],
    'stretching': ['stretching', 'wake-up'],
    'gaming':     ['gaming'],
    'love':       ['love'],
    'cool':       ['cool'],
    'error':      ['error', 'error-crash', 'confused', 'timeout', 'partial', 'interrupted', 'retrying', 'offline', 'rate-limited'],
    'excited':    ['excited'],
    'spawning':   ['delegating', 'handoff'],
    # Drawn and shipped, not yet wired to a trigger in useMascotState.
    'asking':     ['asking'],
    'waiting':    ['waiting-approval', 'waiting-long', 'waiting-network'],
    'speaking':   ['speaking', 'streaming'],
    'listening':  ['listening', 'listening-headset'],
    'blocked':    ['no-key', 'locked'],
    'scheduling': ['scheduling'],
    'storing':    ['remembering-store'],
}


def main():
    man = json.load(open(os.path.join(SRC, 'manifest.json')))
    used = sorted({a for v in VARIANTS.values() for a in v})
    missing = [a for a in used if a not in man]
    assert not missing, missing
    unused = sorted(set(man) - set(used))
    assert not unused, f'animations not mapped to any state: {unused}'

    # 1. the sheet: every drawn frame once, row-major, 16 per row
    frames = []            # (anim, path)
    ticks = {}             # anim -> [sheet index per 160ms tick]
    for anim in used:
        files = sorted(glob.glob(os.path.join(SRC, anim, '*.png')))
        durs = man[anim]['durations_ms']
        assert len(durs) == len(files), anim
        seq = []
        for f, d in zip(files, durs):
            idx = len(frames); frames.append((anim, f))
            seq += [idx] * max(1, round(d / FRAME_MS))
        ticks[anim] = seq
    rows = (len(frames) + COLS - 1) // COLS
    sheet = Image.new('RGBA', (COLS * N, rows * N), (0, 0, 0, 0))
    for i, (_, f) in enumerate(frames):
        im = Image.open(f).convert('RGBA')
        assert im.size == (N, N), f
        sheet.paste(im, ((i % COLS) * N, (i // COLS) * N))
    sheet.save(os.path.join(DST, 'sheet.png'), optimize=True)

    # 2. the index
    def const(a): return 'A_' + a.upper().replace('-', '_')
    out = ['// GENERATED by scripts/mascot/v2/to_frames_ts.py from scripts/mascot/v2/astra/. Do not edit;',
           '// change build.blender.py (the poses) or to_frames_ts.py (the state mapping) and regenerate.',
           '', 'export type MascotState =']
    names = list(VARIANTS)
    for i in range(0, len(names), 6):
        out.append('  | ' + ' | '.join(f"'{n}'" for n in names[i:i + 6]))
    out[-1] += ';'
    out += ['',
            f'/** One drawn frame is {N}x{N}; sheet.png holds {len(frames)} of them, {COLS} per row. */',
            f'export const FRAME_W = {N};', f'export const FRAME_H = {N};',
            f'export const SHEET_COLS = {COLS};', f'export const FRAME_COUNT = {len(frames)};',
            '',
            '/** A frame index into sheet.png, repeated once per renderer tick it is held for. */',
            'export type Frame = number;', '']
    for anim in used:
        out.append(f'// {anim}: {len(man[anim]["durations_ms"])} drawn frames at {man[anim]["fps"]} fps, '
                   f'durations {man[anim]["durations_ms"]} ms')
        out.append(f'const {const(anim)}: Frame[] = [{", ".join(map(str, ticks[anim]))}];')
    out += ['', 'export const VARIANTS: Record<MascotState, Frame[][]> = {']
    for state, anims in VARIANTS.items():
        out.append(f"  {state}: [{', '.join(const(a) for a in anims)}],")
    out += ['};', '', 'export const FRAMES: Record<MascotState, Frame[]> = {']
    for state in VARIANTS:
        out.append(f'  {state}: VARIANTS.{state}[0],')
    out += ['};', '']
    with open(os.path.join(DST, 'frames.ts'), 'w', newline='\n') as fh:
        fh.write('\n'.join(out))
    print(f'sheet {sheet.size}, {len(frames)} frames, {len(used)} animations, {len(VARIANTS)} states')


if __name__ == '__main__':
    main()
