// Generated by scripts/mascot/finish-32.lua from cinderpaw-32.aseprite.
// Do not edit. Our creature: one body, 8 faces, 9 props, 23 states.
// 32px art, shown at 64 (DISPLAY in CinderpawMascot).

import f_idle_1 from './states/idle-1.png';
import f_idle_2 from './states/idle-2.png';
import f_idle_3 from './states/idle-3.png';
import f_idle_4 from './states/idle-4.png';
import f_typing_1 from './states/typing-1.png';
import f_thinking_1 from './states/thinking-1.png';
import f_thinking_2 from './states/thinking-2.png';
import f_calling_1 from './states/calling-1.png';
import f_calling_2 from './states/calling-2.png';
import f_done_1 from './states/done-1.png';
import f_done_2 from './states/done-2.png';
import f_running_1 from './states/running-1.png';
import f_wave_1 from './states/wave-1.png';
import f_sleep_1 from './states/sleep-1.png';
import f_sleep_2 from './states/sleep-2.png';
import f_surprised_1 from './states/surprised-1.png';
import f_curious_1 from './states/curious-1.png';
import f_celebrate_1 from './states/celebrate-1.png';
import f_celebrate_2 from './states/celebrate-2.png';
import f_reading_1 from './states/reading-1.png';
import f_searching_1 from './states/searching-1.png';
import f_building_1 from './states/building-1.png';
import f_writing_1 from './states/writing-1.png';
import f_stretching_1 from './states/stretching-1.png';
import f_gaming_1 from './states/gaming-1.png';
import f_love_1 from './states/love-1.png';
import f_cool_1 from './states/cool-1.png';
import f_error_1 from './states/error-1.png';
import f_error_2 from './states/error-2.png';
import f_excited_1 from './states/excited-1.png';
import f_spawning_1 from './states/spawning-1.png';
import f_meditating_1 from './states/meditating-1.png';

export type MascotState =
  | 'idle' | 'typing' | 'thinking' | 'calling' | 'done' | 'running'
  | 'wave' | 'sleep' | 'surprised' | 'curious' | 'celebrate'
  | 'reading' | 'searching' | 'building' | 'writing'
  | 'stretching' | 'gaming' | 'love' | 'cool' | 'error' | 'excited'
  | 'spawning' | 'meditating';

export const FRAME_W = 32;
export const FRAME_H = 32;

const ART: Record<string, string> = {
  'idle-1': f_idle_1,
  'idle-2': f_idle_2,
  'idle-3': f_idle_3,
  'idle-4': f_idle_4,
  'typing-1': f_typing_1,
  'thinking-1': f_thinking_1,
  'thinking-2': f_thinking_2,
  'calling-1': f_calling_1,
  'calling-2': f_calling_2,
  'done-1': f_done_1,
  'done-2': f_done_2,
  'running-1': f_running_1,
  'wave-1': f_wave_1,
  'sleep-1': f_sleep_1,
  'sleep-2': f_sleep_2,
  'surprised-1': f_surprised_1,
  'curious-1': f_curious_1,
  'celebrate-1': f_celebrate_1,
  'celebrate-2': f_celebrate_2,
  'reading-1': f_reading_1,
  'searching-1': f_searching_1,
  'building-1': f_building_1,
  'writing-1': f_writing_1,
  'stretching-1': f_stretching_1,
  'gaming-1': f_gaming_1,
  'love-1': f_love_1,
  'cool-1': f_cool_1,
  'error-1': f_error_1,
  'error-2': f_error_2,
  'excited-1': f_excited_1,
  'spawning-1': f_spawning_1,
  'meditating-1': f_meditating_1,
};

export const GROUPS: Record<MascotState, string[]> = {
  idle: ['idle-1', 'idle-2', 'idle-3', 'idle-4'],
  typing: ['typing-1'],
  thinking: ['thinking-1', 'thinking-2'],
  calling: ['calling-1', 'calling-2'],
  done: ['done-1', 'done-2'],
  running: ['running-1'],
  wave: ['wave-1'],
  sleep: ['sleep-1', 'sleep-2'],
  surprised: ['surprised-1'],
  curious: ['curious-1'],
  celebrate: ['celebrate-1', 'celebrate-2'],
  reading: ['reading-1'],
  searching: ['searching-1'],
  building: ['building-1'],
  writing: ['writing-1'],
  stretching: ['stretching-1'],
  gaming: ['gaming-1'],
  love: ['love-1'],
  cool: ['cool-1'],
  error: ['error-1', 'error-2'],
  excited: ['excited-1'],
  spawning: ['spawning-1'],
  meditating: ['meditating-1'],
};

// Frame cycling: multi-frame states animate, single-frame states hold.
// Pure function of (state, tick): same tick, same frame, always.
export function frameFor(state: MascotState, tick: number): string {
  const group = GROUPS[state] ?? GROUPS.idle;
  return group[((tick % group.length) + group.length) % group.length];
}
export function artUrl(name: string): string {
  const url = ART[name];
  if (!url) throw new Error('unknown state frame: ' + name);
  return url;
}
