// GENERATED by scripts/mascot/v3/pack_frames.py from scripts/mascot/v3/frames/. Do not edit;
// change ANIMS in build_character.py (the motion) or pack_frames.py (marks, state mapping) and regenerate.

export type MascotState =
  | 'idle' | 'typing' | 'thinking' | 'calling' | 'done' | 'running'
  | 'wave' | 'sleep' | 'surprised' | 'curious' | 'celebrate' | 'reading'
  | 'searching' | 'building' | 'writing' | 'stretching' | 'gaming' | 'love'
  | 'cool' | 'error' | 'excited' | 'spawning' | 'asking' | 'waiting'
  | 'speaking' | 'listening' | 'blocked' | 'scheduling' | 'storing';

/** One drawn frame is 256x256 (the clay character, rendered in Blender); sheet.webp holds
 *  112 of them, 16 per row. */
export const FRAME_W = 256;
export const FRAME_H = 256;
export const SHEET_COLS = 16;
export const FRAME_COUNT = 112;
/** The renderer's clock: 24 ticks a second. Each index below is held for one tick. */
export const TICK_MS = 42;

/** A frame index into sheet.webp. */
export type Frame = number;

// curious: 16 drawn frames at 8 fps
const A_CURIOUS: Frame[] = [0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10, 10, 11, 11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15];
// focused: 12 drawn frames at 12 fps
const A_FOCUSED: Frame[] = [16, 16, 17, 17, 18, 18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25, 25, 26, 26, 27, 27];
// happy: 12 drawn frames at 12 fps
const A_HAPPY: Frame[] = [28, 28, 29, 29, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34, 35, 35, 36, 36, 37, 37, 38, 38, 39, 39];
// idle: 16 drawn frames at 8 fps
const A_IDLE: Frame[] = [40, 40, 40, 41, 41, 41, 42, 42, 42, 43, 43, 43, 44, 44, 44, 45, 45, 45, 46, 46, 46, 47, 47, 47, 48, 48, 48, 49, 49, 49, 50, 50, 50, 51, 51, 51, 52, 52, 52, 53, 53, 53, 54, 54, 54, 55, 55, 55];
// sleepy: 16 drawn frames at 6 fps
const A_SLEEPY: Frame[] = [56, 56, 56, 56, 57, 57, 57, 57, 58, 58, 58, 58, 59, 59, 59, 59, 60, 60, 60, 60, 61, 61, 61, 61, 62, 62, 62, 62, 63, 63, 63, 63, 64, 64, 64, 64, 65, 65, 65, 65, 66, 66, 66, 66, 67, 67, 67, 67, 68, 68, 68, 68, 69, 69, 69, 69, 70, 70, 70, 70, 71, 71, 71, 71];
// surprised: 12 drawn frames at 12 fps
const A_SURPRISED: Frame[] = [72, 72, 73, 73, 74, 74, 75, 75, 76, 76, 77, 77, 78, 78, 79, 79, 80, 80, 81, 81, 82, 82, 83, 83];
// thinking: 16 drawn frames at 8 fps
const A_THINKING: Frame[] = [84, 84, 84, 85, 85, 85, 86, 86, 86, 87, 87, 87, 88, 88, 88, 89, 89, 89, 90, 90, 90, 91, 91, 91, 92, 92, 92, 93, 93, 93, 94, 94, 94, 95, 95, 95, 96, 96, 96, 97, 97, 97, 98, 98, 98, 99, 99, 99];
// waving: 12 drawn frames at 12 fps
const A_WAVING: Frame[] = [100, 100, 101, 101, 102, 102, 103, 103, 104, 104, 105, 105, 106, 106, 107, 107, 108, 108, 109, 109, 110, 110, 111, 111];

export const VARIANTS: Record<MascotState, Frame[][]> = {
  idle: [A_IDLE],
  typing: [A_FOCUSED],
  thinking: [A_THINKING],
  calling: [A_FOCUSED],
  done: [A_HAPPY],
  running: [A_FOCUSED],
  wave: [A_WAVING],
  sleep: [A_SLEEPY],
  surprised: [A_SURPRISED],
  curious: [A_CURIOUS],
  celebrate: [A_HAPPY],
  reading: [A_FOCUSED],
  searching: [A_CURIOUS],
  building: [A_FOCUSED],
  writing: [A_FOCUSED],
  stretching: [A_IDLE],
  gaming: [A_FOCUSED],
  love: [A_HAPPY],
  cool: [A_IDLE],
  error: [A_SURPRISED],
  excited: [A_HAPPY],
  spawning: [A_WAVING],
  asking: [A_CURIOUS],
  waiting: [A_IDLE],
  speaking: [A_IDLE],
  listening: [A_CURIOUS],
  blocked: [A_THINKING],
  scheduling: [A_THINKING],
  storing: [A_THINKING],
};

export const FRAMES: Record<MascotState, Frame[]> = {
  idle: VARIANTS.idle[0],
  typing: VARIANTS.typing[0],
  thinking: VARIANTS.thinking[0],
  calling: VARIANTS.calling[0],
  done: VARIANTS.done[0],
  running: VARIANTS.running[0],
  wave: VARIANTS.wave[0],
  sleep: VARIANTS.sleep[0],
  surprised: VARIANTS.surprised[0],
  curious: VARIANTS.curious[0],
  celebrate: VARIANTS.celebrate[0],
  reading: VARIANTS.reading[0],
  searching: VARIANTS.searching[0],
  building: VARIANTS.building[0],
  writing: VARIANTS.writing[0],
  stretching: VARIANTS.stretching[0],
  gaming: VARIANTS.gaming[0],
  love: VARIANTS.love[0],
  cool: VARIANTS.cool[0],
  error: VARIANTS.error[0],
  excited: VARIANTS.excited[0],
  spawning: VARIANTS.spawning[0],
  asking: VARIANTS.asking[0],
  waiting: VARIANTS.waiting[0],
  speaking: VARIANTS.speaking[0],
  listening: VARIANTS.listening[0],
  blocked: VARIANTS.blocked[0],
  scheduling: VARIANTS.scheduling[0],
  storing: VARIANTS.storing[0],
};
