// GENERATED by scripts/mascot/v2/to_frames_ts.py from scripts/mascot/v2/astra/. Do not edit;
// change build.blender.py (the poses) or to_frames_ts.py (the state mapping) and regenerate.

export type MascotState =
  | 'idle' | 'typing' | 'thinking' | 'calling' | 'done' | 'running'
  | 'wave' | 'sleep' | 'surprised' | 'curious' | 'celebrate' | 'reading'
  | 'searching' | 'building' | 'writing' | 'stretching' | 'gaming' | 'love'
  | 'cool' | 'error' | 'excited' | 'spawning' | 'asking' | 'waiting'
  | 'speaking' | 'listening' | 'blocked' | 'scheduling' | 'storing';

/** One drawn frame is 64x64; sheet.png holds 302 of them, 16 per row. */
export const FRAME_W = 64;
export const FRAME_H = 64;
export const SHEET_COLS = 16;
export const FRAME_COUNT = 302;

/** A frame index into sheet.png, repeated once per renderer tick it is held for. */
export type Frame = number;

// asking: 4 drawn frames at 4 fps, durations [750, 250, 500, 250] ms
const A_ASKING: Frame[] = [0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 3, 3];
// browsing: 4 drawn frames at 5 fps, durations [400, 200, 200, 400] ms
const A_BROWSING: Frame[] = [4, 4, 5, 6, 7, 7];
// building: 4 drawn frames at 6 fps, durations [333, 167, 167, 333] ms
const A_BUILDING: Frame[] = [8, 8, 9, 10, 11, 11];
// calling: 4 drawn frames at 6 fps, durations [333, 167, 167, 667] ms
const A_CALLING: Frame[] = [12, 12, 13, 14, 15, 15, 15, 15];
// calling-phone: 4 drawn frames at 6 fps, durations [333, 167, 167, 333] ms
const A_CALLING_PHONE: Frame[] = [16, 16, 17, 18, 19, 19];
// celebrate: 4 drawn frames at 8 fps, durations [250, 125, 250, 125] ms
const A_CELEBRATE: Frame[] = [20, 20, 21, 22, 22, 23];
// committing: 4 drawn frames at 4 fps, durations [500, 250, 250, 1000] ms
const A_COMMITTING: Frame[] = [24, 24, 24, 25, 25, 26, 26, 27, 27, 27, 27, 27, 27];
// confused: 4 drawn frames at 4 fps, durations [500, 250, 250, 500] ms
const A_CONFUSED: Frame[] = [28, 28, 28, 29, 29, 30, 30, 31, 31, 31];
// cool: 3 drawn frames at 3 fps, durations [667, 333, 1333] ms
const A_COOL: Frame[] = [32, 32, 32, 32, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34];
// deciding: 4 drawn frames at 6 fps, durations [333, 167, 333, 167] ms
const A_DECIDING: Frame[] = [35, 35, 36, 37, 37, 38];
// delegating: 4 drawn frames at 5 fps, durations [400, 200, 200, 800] ms
const A_DELEGATING: Frame[] = [39, 39, 40, 41, 42, 42, 42, 42, 42];
// done: 4 drawn frames at 6 fps, durations [333, 167, 333, 333] ms
const A_DONE: Frame[] = [43, 43, 44, 45, 45, 46, 46];
// done-nod: 3 drawn frames at 3 fps, durations [667, 333, 1333] ms
const A_DONE_NOD: Frame[] = [47, 47, 47, 47, 48, 48, 49, 49, 49, 49, 49, 49, 49, 49];
// downloading: 5 drawn frames at 4 fps, durations [500, 250, 250, 250, 500] ms
const A_DOWNLOADING: Frame[] = [50, 50, 50, 51, 51, 52, 52, 53, 53, 54, 54, 54];
// drag-drop: 3 drawn frames at 3 fps, durations [667, 333, 1333] ms
const A_DRAG_DROP: Frame[] = [55, 55, 55, 55, 56, 56, 57, 57, 57, 57, 57, 57, 57, 57];
// dreaming: 6 drawn frames at 2 fps, durations [1000, 500, 500, 500, 500, 1000] ms
const A_DREAMING: Frame[] = [58, 58, 58, 58, 58, 58, 59, 59, 59, 60, 60, 60, 61, 61, 61, 62, 62, 62, 63, 63, 63, 63, 63, 63];
// error: 3 drawn frames at 4 fps, durations [500, 250, 750] ms
const A_ERROR: Frame[] = [64, 64, 64, 65, 65, 66, 66, 66, 66, 66];
// error-crash: 4 drawn frames at 4 fps, durations [500, 250, 250, 500] ms
const A_ERROR_CRASH: Frame[] = [67, 67, 67, 68, 68, 69, 69, 70, 70, 70];
// excited: 4 drawn frames at 8 fps, durations [250, 125, 250, 125] ms
const A_EXCITED: Frame[] = [71, 71, 72, 73, 73, 74];
// exporting: 4 drawn frames at 5 fps, durations [400, 200, 200, 800] ms
const A_EXPORTING: Frame[] = [75, 75, 76, 77, 78, 78, 78, 78, 78];
// fetching-url: 4 drawn frames at 4 fps, durations [500, 250, 250, 500] ms
const A_FETCHING_URL: Frame[] = [79, 79, 79, 80, 80, 81, 81, 82, 82, 82];
// gaming: 4 drawn frames at 4 fps, durations [500, 250, 250, 500] ms
const A_GAMING: Frame[] = [83, 83, 83, 84, 84, 85, 85, 86, 86, 86];
// goodbye: 4 drawn frames at 4 fps, durations [500, 250, 250, 1000] ms
const A_GOODBYE: Frame[] = [87, 87, 87, 88, 88, 89, 89, 90, 90, 90, 90, 90, 90];
// handoff: 4 drawn frames at 4 fps, durations [500, 250, 250, 1000] ms
const A_HANDOFF: Frame[] = [91, 91, 91, 92, 92, 93, 93, 94, 94, 94, 94, 94, 94];
// idle: 8 drawn frames at 6 fps, durations [500, 167, 167, 333, 167, 167, 167, 333] ms
const A_IDLE: Frame[] = [95, 95, 95, 96, 97, 98, 98, 99, 100, 101, 102, 102];
// idle-look-around: 6 drawn frames at 4 fps, durations [500, 250, 750, 250, 750, 500] ms
const A_IDLE_LOOK_AROUND: Frame[] = [103, 103, 103, 104, 104, 105, 105, 105, 105, 105, 106, 106, 107, 107, 107, 107, 107, 108, 108, 108];
// idle-scratch: 6 drawn frames at 6 fps, durations [333, 167, 167, 167, 167, 500] ms
const A_IDLE_SCRATCH: Frame[] = [109, 109, 110, 111, 112, 113, 114, 114, 114];
// idle-sit: 6 drawn frames at 4 fps, durations [500, 250, 750, 250, 250, 500] ms
const A_IDLE_SIT: Frame[] = [115, 115, 115, 116, 116, 117, 117, 117, 117, 117, 118, 118, 119, 119, 120, 120, 120];
// idle-yawn: 5 drawn frames at 4 fps, durations [500, 250, 250, 1000, 750] ms
const A_IDLE_YAWN: Frame[] = [121, 121, 121, 122, 122, 123, 123, 124, 124, 124, 124, 124, 124, 125, 125, 125, 125, 125];
// image-generating: 5 drawn frames at 4 fps, durations [500, 250, 250, 250, 1000] ms
const A_IMAGE_GENERATING: Frame[] = [126, 126, 126, 127, 127, 128, 128, 129, 129, 130, 130, 130, 130, 130, 130];
// installing-skill: 4 drawn frames at 5 fps, durations [400, 200, 200, 800] ms
const A_INSTALLING_SKILL: Frame[] = [131, 131, 132, 133, 134, 134, 134, 134, 134];
// interrupted: 4 drawn frames at 4 fps, durations [500, 250, 250, 1000] ms
const A_INTERRUPTED: Frame[] = [135, 135, 135, 136, 136, 137, 137, 138, 138, 138, 138, 138, 138];
// listening: 4 drawn frames at 4 fps, durations [500, 250, 250, 500] ms
const A_LISTENING: Frame[] = [139, 139, 139, 140, 140, 141, 141, 142, 142, 142];
// listening-headset: 6 drawn frames at 6 fps, durations [333, 167, 167, 167, 167, 333] ms
const A_LISTENING_HEADSET: Frame[] = [143, 143, 144, 145, 146, 147, 148, 148];
// locked: 3 drawn frames at 3 fps, durations [667, 333, 1333] ms
const A_LOCKED: Frame[] = [149, 149, 149, 149, 150, 150, 151, 151, 151, 151, 151, 151, 151, 151];
// love: 4 drawn frames at 4 fps, durations [500, 250, 250, 500] ms
const A_LOVE: Frame[] = [152, 152, 152, 153, 153, 154, 154, 155, 155, 155];
// no-key: 3 drawn frames at 3 fps, durations [1000, 333, 667] ms
const A_NO_KEY: Frame[] = [156, 156, 156, 156, 156, 156, 157, 157, 158, 158, 158, 158];
// offline: 3 drawn frames at 2 fps, durations [1500, 500, 1000] ms
const A_OFFLINE: Frame[] = [159, 159, 159, 159, 159, 159, 159, 159, 159, 160, 160, 160, 161, 161, 161, 161, 161, 161];
// partial: 3 drawn frames at 3 fps, durations [667, 333, 1333] ms
const A_PARTIAL: Frame[] = [162, 162, 162, 162, 163, 163, 164, 164, 164, 164, 164, 164, 164, 164];
// paste: 3 drawn frames at 3 fps, durations [667, 333, 1333] ms
const A_PASTE: Frame[] = [165, 165, 165, 165, 166, 166, 167, 167, 167, 167, 167, 167, 167, 167];
// planning: 4 drawn frames at 3 fps, durations [667, 333, 333, 1333] ms
const A_PLANNING: Frame[] = [168, 168, 168, 168, 169, 169, 170, 170, 171, 171, 171, 171, 171, 171, 171, 171];
// rate-limited: 3 drawn frames at 2 fps, durations [1500, 500, 1000] ms
const A_RATE_LIMITED: Frame[] = [172, 172, 172, 172, 172, 172, 172, 172, 172, 173, 173, 173, 174, 174, 174, 174, 174, 174];
// reading: 4 drawn frames at 3 fps, durations [667, 333, 333, 667] ms
const A_READING: Frame[] = [175, 175, 175, 175, 176, 176, 177, 177, 178, 178, 178, 178];
// reading-attachment: 4 drawn frames at 4 fps, durations [500, 250, 250, 500] ms
const A_READING_ATTACHMENT: Frame[] = [179, 179, 179, 180, 180, 181, 181, 182, 182, 182];
// reading-pdf: 4 drawn frames at 3 fps, durations [667, 333, 333, 667] ms
const A_READING_PDF: Frame[] = [183, 183, 183, 183, 184, 184, 185, 185, 186, 186, 186, 186];
// receiving-message: 4 drawn frames at 6 fps, durations [333, 167, 167, 667] ms
const A_RECEIVING_MESSAGE: Frame[] = [187, 187, 188, 189, 190, 190, 190, 190];
// remembering: 4 drawn frames at 4 fps, durations [500, 250, 500, 250] ms
const A_REMEMBERING: Frame[] = [191, 191, 191, 192, 192, 193, 193, 193, 194, 194];
// remembering-store: 4 drawn frames at 4 fps, durations [500, 250, 250, 1000] ms
const A_REMEMBERING_STORE: Frame[] = [195, 195, 195, 196, 196, 197, 197, 198, 198, 198, 198, 198, 198];
// retrying: 4 drawn frames at 4 fps, durations [500, 250, 250, 500] ms
const A_RETRYING: Frame[] = [199, 199, 199, 200, 200, 201, 201, 202, 202, 202];
// running-shell: 4 drawn frames at 4 fps, durations [500, 250, 250, 500] ms
const A_RUNNING_SHELL: Frame[] = [203, 203, 203, 204, 204, 205, 205, 206, 206, 206];
// scheduling: 4 drawn frames at 3 fps, durations [667, 333, 333, 667] ms
const A_SCHEDULING: Frame[] = [207, 207, 207, 207, 208, 208, 209, 209, 210, 210, 210, 210];
// searching: 4 drawn frames at 5 fps, durations [400, 200, 200, 400] ms
const A_SEARCHING: Frame[] = [211, 211, 212, 213, 214, 214];
// searching-deep: 4 drawn frames at 4 fps, durations [500, 250, 250, 500] ms
const A_SEARCHING_DEEP: Frame[] = [215, 215, 215, 216, 216, 217, 217, 218, 218, 218];
// sending-file: 4 drawn frames at 8 fps, durations [250, 125, 125, 500] ms
const A_SENDING_FILE: Frame[] = [219, 219, 220, 221, 222, 222, 222];
// sleep: 6 drawn frames at 3 fps, durations [667, 333, 333, 333, 333, 667] ms
const A_SLEEP: Frame[] = [223, 223, 223, 223, 224, 224, 225, 225, 226, 226, 227, 227, 228, 228, 228, 228];
// speaking: 4 drawn frames at 8 fps, durations [250, 125, 125, 250] ms
const A_SPEAKING: Frame[] = [229, 229, 230, 231, 232, 232];
// streaming: 4 drawn frames at 8 fps, durations [250, 125, 250, 125] ms
const A_STREAMING: Frame[] = [233, 233, 234, 235, 235, 236];
// stretching: 5 drawn frames at 5 fps, durations [400, 200, 200, 800, 600] ms
const A_STRETCHING: Frame[] = [237, 237, 238, 239, 240, 240, 240, 240, 240, 241, 241, 241, 241];
// surprised: 3 drawn frames at 3 fps, durations [667, 333, 1333] ms
const A_SURPRISED: Frame[] = [242, 242, 242, 242, 243, 243, 244, 244, 244, 244, 244, 244, 244, 244];
// testing: 4 drawn frames at 5 fps, durations [400, 200, 200, 400] ms
const A_TESTING: Frame[] = [245, 245, 246, 247, 248, 248];
// tests-green: 3 drawn frames at 6 fps, durations [333, 167, 667] ms
const A_TESTS_GREEN: Frame[] = [249, 249, 250, 251, 251, 251, 251];
// thinking: 4 drawn frames at 4 fps, durations [500, 250, 500, 500] ms
const A_THINKING: Frame[] = [252, 252, 252, 253, 253, 254, 254, 254, 255, 255, 255];
// thinking-deep: 6 drawn frames at 3 fps, durations [667, 333, 333, 1000, 333, 667] ms
const A_THINKING_DEEP: Frame[] = [256, 256, 256, 256, 257, 257, 258, 258, 259, 259, 259, 259, 259, 259, 260, 260, 261, 261, 261, 261];
// thinking-scratch-head: 4 drawn frames at 4 fps, durations [500, 250, 500, 250] ms
const A_THINKING_SCRATCH_HEAD: Frame[] = [262, 262, 262, 263, 263, 264, 264, 264, 265, 265];
// timeout: 3 drawn frames at 3 fps, durations [667, 333, 1333] ms
const A_TIMEOUT: Frame[] = [266, 266, 266, 266, 267, 267, 268, 268, 268, 268, 268, 268, 268, 268];
// typing: 4 drawn frames at 8 fps, durations [250, 125, 250, 125] ms
const A_TYPING: Frame[] = [269, 269, 270, 271, 271, 272];
// waiting-approval: 4 drawn frames at 3 fps, durations [1667, 667, 333, 333] ms
const A_WAITING_APPROVAL: Frame[] = [273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 274, 274, 274, 274, 275, 275, 276, 276];
// waiting-long: 6 drawn frames at 2 fps, durations [1500, 500, 500, 1500, 500, 1000] ms
const A_WAITING_LONG: Frame[] = [277, 277, 277, 277, 277, 277, 277, 277, 277, 278, 278, 278, 279, 279, 279, 280, 280, 280, 280, 280, 280, 280, 280, 280, 281, 281, 281, 282, 282, 282, 282, 282, 282];
// waiting-network: 3 drawn frames at 4 fps, durations [500, 250, 500] ms
const A_WAITING_NETWORK: Frame[] = [283, 283, 283, 284, 284, 285, 285, 285];
// wake-up: 4 drawn frames at 8 fps, durations [375, 125, 125, 375] ms
const A_WAKE_UP: Frame[] = [286, 286, 287, 288, 289, 289];
// wave: 4 drawn frames at 4 fps, durations [500, 250, 250, 500] ms
const A_WAVE: Frame[] = [290, 290, 290, 291, 291, 292, 292, 293, 293, 293];
// writing: 4 drawn frames at 6 fps, durations [333, 167, 167, 333] ms
const A_WRITING: Frame[] = [294, 294, 295, 296, 297, 297];
// writing-code: 4 drawn frames at 8 fps, durations [250, 125, 125, 250] ms
const A_WRITING_CODE: Frame[] = [298, 298, 299, 300, 301, 301];

export const VARIANTS: Record<MascotState, Frame[][]> = {
  idle: [A_IDLE, A_IDLE_LOOK_AROUND, A_IDLE_SCRATCH, A_IDLE_YAWN, A_IDLE_SIT],
  typing: [A_TYPING],
  thinking: [A_THINKING, A_THINKING_DEEP, A_THINKING_SCRATCH_HEAD, A_PLANNING, A_REMEMBERING, A_DECIDING],
  calling: [A_CALLING, A_CALLING_PHONE, A_RECEIVING_MESSAGE, A_SENDING_FILE],
  done: [A_DONE, A_DONE_NOD, A_TESTS_GREEN],
  running: [A_RUNNING_SHELL, A_COMMITTING, A_INSTALLING_SKILL, A_DOWNLOADING],
  wave: [A_WAVE, A_GOODBYE],
  sleep: [A_SLEEP, A_DREAMING],
  surprised: [A_SURPRISED, A_DRAG_DROP],
  curious: [A_IDLE_LOOK_AROUND, A_LISTENING],
  celebrate: [A_CELEBRATE, A_EXCITED],
  reading: [A_READING, A_READING_PDF, A_READING_ATTACHMENT, A_BROWSING, A_PASTE],
  searching: [A_SEARCHING, A_SEARCHING_DEEP, A_FETCHING_URL],
  building: [A_BUILDING, A_TESTING],
  writing: [A_WRITING, A_WRITING_CODE, A_IMAGE_GENERATING, A_EXPORTING],
  stretching: [A_STRETCHING, A_WAKE_UP],
  gaming: [A_GAMING],
  love: [A_LOVE],
  cool: [A_COOL],
  error: [A_ERROR, A_ERROR_CRASH, A_CONFUSED, A_TIMEOUT, A_PARTIAL, A_INTERRUPTED, A_RETRYING, A_OFFLINE, A_RATE_LIMITED],
  excited: [A_EXCITED],
  spawning: [A_DELEGATING, A_HANDOFF],
  asking: [A_ASKING],
  waiting: [A_WAITING_APPROVAL, A_WAITING_LONG, A_WAITING_NETWORK],
  speaking: [A_SPEAKING, A_STREAMING],
  listening: [A_LISTENING, A_LISTENING_HEADSET],
  blocked: [A_NO_KEY, A_LOCKED],
  scheduling: [A_SCHEDULING],
  storing: [A_REMEMBERING_STORE],
};

export const FRAMES: Record<MascotState, Frame[]> = {
  idle: VARIANTS.idle[0],
  typing: VARIANTS.typing[0],
  thinking: VARIANTS.thinking[0],
  calling: VARIANTS.calling[0],
  done: VARIANTS.done[0],
  running: VARIANTS.running[0],
  wave: VARIANTS.wave[0],
  sleep: VARIANTS.sleep[0],
  surprised: VARIANTS.surprised[0],
  curious: VARIANTS.curious[0],
  celebrate: VARIANTS.celebrate[0],
  reading: VARIANTS.reading[0],
  searching: VARIANTS.searching[0],
  building: VARIANTS.building[0],
  writing: VARIANTS.writing[0],
  stretching: VARIANTS.stretching[0],
  gaming: VARIANTS.gaming[0],
  love: VARIANTS.love[0],
  cool: VARIANTS.cool[0],
  error: VARIANTS.error[0],
  excited: VARIANTS.excited[0],
  spawning: VARIANTS.spawning[0],
  asking: VARIANTS.asking[0],
  waiting: VARIANTS.waiting[0],
  speaking: VARIANTS.speaking[0],
  listening: VARIANTS.listening[0],
  blocked: VARIANTS.blocked[0],
  scheduling: VARIANTS.scheduling[0],
  storing: VARIANTS.storing[0],
};
