import io, json, re

M = '../../frontend-react/src/components/chat/mascot/'
b = json.loads(io.open('built.json', encoding='utf-8').read())
bodies, scenes, variants = b['bodies'], b['scenes'], b['variants']

# ---------------- frames.ts ----------------
src = io.open(M + 'frames.ts', encoding='utf-8').read()
_m = re.search(r'\nconst \w+: Frame = \[', src)
head = src[:_m.start() + 1]  # type, sizes, palette, body shade, Frame type

note = '''/*
 * The creature, and only the creature.
 *
 * There used to be 127 hand-drawn frames here, and a large part of what made
 * them differ was a two-to-four pixel prop carved into the body: a leaf on a
 * tuft, a green dot crossing the belly, a bar over a horn. At sixteen pixels
 * across, an object that small has no silhouette, so none of them read as
 * objects -- they read as damage to the animal, which is exactly how they were
 * described when somebody finally looked.
 *
 * Every prop now lives in `scenes.ts`, in the margin around this sprite, at the
 * size the reference pack drew it. What is left in here is a body, and it is
 * built the way the reference builds one: a solid block with its features CUT
 * OUT of it. The mouth is a hole. The legs are holes. Only the eyes are ink.
 * There is no outline, and that is the point -- an outline has to be redrawn to
 * change shape, which is why all 127 old frames shared one silhouette no matter
 * what the creature was supposed to be feeling.
 *
 * The two tufts stay. They are ours, they are deliberately ambiguous between
 * ears and horns, and they were never the problem.
 *
 * Generated by `scratchpad/build_body.py`; the old sheet is in git at 8ad7ed5.
 */

'''
parts = [head + note]
for name in sorted(bodies):
    rows = ',\n  '.join("'" + r + "'" for r in bodies[name])
    parts.append('const %s: Frame = [\n  %s\n];\n' % (name, rows))

parts.append('\nexport const VARIANTS: Record<MascotState, Frame[][]> = {')
for st, v in variants.items():
    parts.append('  %-13s[%s],' % (st + ':', ','.join('[' + ','.join(g) + ']' for g in v)))
parts.append('};\n')
parts.append('''export const FRAMES: Record<MascotState, Frame[]> = Object.fromEntries(
  (Object.keys(VARIANTS) as MascotState[]).map((s) => [s, VARIANTS[s][0]]),
) as Record<MascotState, Frame[]>;
''')
io.open(M + 'frames.ts', 'w', encoding='utf-8', newline='\n').write('\n'.join(parts))

# ---------------- scenes.ts ----------------
L = ['''/**
 * The scene around the creature, lifted out of the reference pack.
 *
 * The 75 illustrations these sprites were drawn from share one body and put
 * everything else AROUND it: the blocks below, the Z's above, the window
 * beside. Each entry here was produced mechanically -- their character was
 * found and subtracted, and what remained was anchored to the side of OUR body
 * it had been composed on, then slid as one piece to somewhere it fits with
 * three cells of air around the creature. Nothing was traced by hand, and their
 * character is in none of it.
 *
 * A state can carry several scenes. That is where a state's variety comes from
 * now: not from redrawing the creature, but from what is standing next to it,
 * which is how the pack was composed in the first place.
 *
 * Coordinates are canvas cells, the space `effects.ts` draws in.
 * Regenerate with `scratchpad/build_all.py`.
 */
import type { MascotState } from './frames';
import type { EffectPixel } from './effects';

/** x, y, colour. Flat triples rather than objects: there are 1.5k of them. */
export type ScenePixel = readonly [number, number, string];

export const SCENES: Partial<Record<MascotState, readonly (readonly ScenePixel[])[]>> = {''']
for st, group in scenes.items():
    L.append('  %s: [' % st)
    for g in group:
        px = ','.join('[%d,%d,%r]' % (x, y, c) for x, y, c in g['px']).replace("'", '"')
        L.append('    /* %s */ [%s],' % (g['from'], px))
    L.append('  ],')
L.append('''};

/**
 * Which scene, and where it sits this tick.
 *
 * A state with several scenes shows a different one each time it comes round,
 * rather than cycling while you watch: a prop that swaps itself mid-thought is
 * a distraction, and the whole reason the old choreography was deleted was that
 * motion nobody asked for stops being seen. So the choice advances on ENTERING
 * the state, and holds for as long as the state does.
 *
 * The scene also rises and falls a pixel, on a slower count than the body's own
 * bob. Slower on purpose: matched exactly, creature and prop would read as one
 * rigid object being moved by a machine.
 */
let lastState: MascotState | null = null;
let pick = 0;

export function sceneFor(state: MascotState, tick: number): EffectPixel[] {
  const group = SCENES[state];
  if (!group || group.length === 0) return [];
  if (state !== lastState) {
    lastState = state;
    pick = (pick + 1) % group.length;
  }
  const scene = group[pick % group.length];
  const lift = tick % 8 < 4 ? 0 : 1;
  return scene.map(([x, y, color]) => ({ x, y: y + lift, color }));
}''')
io.open(M + 'scenes.ts', 'w', encoding='utf-8', newline='\n').write('\n'.join(L) + '\n')

print('frames.ts : %d bodies, %d states' % (len(bodies), len(variants)))
print('scenes.ts : %d scenes, %d pixels' % (
    sum(len(v) for v in scenes.values()),
    sum(len(g['px']) for v in scenes.values() for g in v)))
