"""Rasterizeaza pachetul Claude Mascot (SVG) in PNG, exact si offline.

Pachetul e arta vectoriala in estetica pixelilor: 17048 de dreptunghiuri
plate + un poligon, culori plate, fara gradiente. Niciun rasterizator de
sistem nu e necesar: citesc dreptunghiurile si le desenez 1 la 1 cu PIL
(fara antialiasing, ca shape-rendering=crispEdges din fisiere).

  python scripts/mascot/raster-pack.py sheet   # plansa de contact in Temp
  python scripts/mascot/raster-pack.py app     # PNG-urile pentru aplicatie
"""

import os
import re
import sys
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
ZIP = r'C:\Users\Darius\Downloads\Claude-Mascot-Pack-SVG.zip'
TMP = r'C:\Users\Darius\AppData\Local\Temp\opencode'
NATIVE = 2000
# Iesirea pentru aplicatie: PNG-uri + index cu maparea pe stari (assign.json).
APP_DIR = os.path.join(HERE, '..', '..', 'frontend-react', 'src',
                       'components', 'chat', 'mascot', 'pack')
APP_SIZE = 128
ASSIGN = os.path.join(HERE, 'assign.json')


def shapes(name):
    with zipfile.ZipFile(ZIP) as f:
        txt = f.read(name).decode('utf-8', 'ignore')
    out = []
    for m in re.finditer(r'<rect\b([^>]*)/?>', txt):
        d = dict(re.findall(r'([\w-]+)="([^"]+)"', m.group(1)))
        out.append(('rect', float(d['x']), float(d['y']),
                    float(d['width']), float(d['height']), d.get('fill', '#000')))
    for m in re.finditer(r'<polygon\b([^>]*)/?>', txt):
        d = dict(re.findall(r'([\w-]+)="([^"]+)"', m.group(1)))
        pts = [float(v) for v in re.findall(r'-?\d+\.?\d*', d['points'])]
        out.append(('poly', list(zip(pts[::2], pts[1::2])), d.get('fill', '#000')))
    return out


def norm_color(c):
    c = c.strip().lower()
    if len(c) == 4 and c[0] == '#':
        return '#' + c[1] * 2 + c[2] * 2 + c[3] * 2
    return c


def rasterize(name, size):
    from PIL import Image, ImageDraw
    items = shapes(name)
    im = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    dr = ImageDraw.Draw(im)
    k = size / NATIVE
    for it in items:
        if it[0] == 'rect':
            _, x, y, w, h, fill = it
            dr.rectangle([round(x * k), round(y * k),
                          round((x + w) * k) - 1, round((y + h) * k) - 1],
                         fill=norm_color(fill))
        else:
            _, pts, fill = it
            dr.polygon([(round(x * k), round(y * k)) for x, y in pts],
                       fill=norm_color(fill))
    return im


def all_names():
    with zipfile.ZipFile(ZIP) as f:
        return sorted(f.namelist())


def app():
    import json
    from PIL import Image
    names = all_names()
    os.makedirs(APP_DIR, exist_ok=True)
    with open(ASSIGN, encoding='utf-8') as f:
        assign = json.load(f)
    # Trei stari n-au ilustratie proprie in pachet; primesc una vecina.
    assign = dict(assign)
    assign.setdefault('gaming', ['lifting-heavy-barbell'])
    assign.setdefault('cool', ['trending-up-pixel'])
    assign.setdefault('spawning', ['idea-lightbulb-pixel'])
    used = sorted({n for v in assign.values() for n in v})
    missing = [n for n in used if n + '.svg' not in names]
    assert not missing, 'lipsesc din zip: %s' % missing
    index = {}
    for n in names:
        stem = n[:-4]
        im = rasterize(n, APP_SIZE)
        bbox = im.getbbox()
        assert bbox, 'ilustratie goala: %s' % n
        im.save(os.path.join(APP_DIR, stem + '.png'))
        index[stem] = {'file': stem + '.png', 'w': im.width, 'h': im.height,
                       'states': sorted(s for s, v in assign.items() if stem in v)}
    with open(os.path.join(APP_DIR, 'index.json'), 'w', encoding='utf-8') as f:
        json.dump(index, f, indent=1, sort_keys=True)
    # Catalogul TypeScript: importuri statice (fara glob, fara config).
    lines = ['// Generated by scripts/mascot/raster-pack.py app. Do not edit.',
             '//',
             '// Art: Claude Mascot Pack (75 pixel illustrations,',
             '// commercial-use licensed). The zip itself is not redistributed;',
             '// these PNGs are rendered from it at 128px for in-app use.',
             '// State names follow scripts/mascot/assign.json.',
             '']
    for i, n in enumerate(names):
        lines.append("import art%d from './pack/%s';" % (i, n[:-4] + '.png'))
    lines += ['',
              'export type MascotState =',
              "  | 'idle' | 'typing' | 'thinking' | 'calling' | 'done' | 'running'",
              "  | 'wave' | 'sleep' | 'surprised' | 'curious' | 'celebrate'",
              "  | 'reading' | 'searching' | 'building' | 'writing'",
              "  | 'stretching' | 'gaming' | 'love' | 'cool' | 'error' | 'excited'",
              "  | 'spawning' | 'meditating';",
              '',
              '// Display size in px. Masters are 128px, shown 1:1.',
              'export const FRAME_W = 128;',
              'export const FRAME_H = 128;',
              '',
              'const ART: Record<string, string> = {']
    for i, n in enumerate(names):
        lines.append("  '%s': art%d," % (n[:-4], i))
    lines += ['};', '',
              'export const PACK: Record<MascotState, string[]> = {']
    for s in ['idle', 'typing', 'thinking', 'calling', 'done', 'running',
              'wave', 'sleep', 'surprised', 'curious', 'celebrate',
              'reading', 'searching', 'building', 'writing',
              'stretching', 'gaming', 'love', 'cool', 'error', 'excited',
              'spawning', 'meditating']:
        lines.append("  %s: [%s]," % (s, ', '.join("'%s'" % v for v in assign[s])))
    lines += ['};', '',
              '// Rotation on ENTERING a state (never mid-state): a state with',
              '// several illustrations shows a different one each visit. Each',
              '// state remembers its own position, so interleaving states',
              '// cannot reset the cycle.',
              'let lastState: MascotState | null = null;',
              'const picks: Partial<Record<MascotState, number>> = {};',
              'export function packFor(state: MascotState): string {',
              '  const group = PACK[state] ?? PACK.idle;',
              '  if (state !== lastState) {',
              '    lastState = state;',
              "    picks[state] = ((picks[state] ?? -1) + 1) % group.length;",
              '  }',
              '  return group[picks[state] ?? 0];',
              '}',
              'export function packUrl(name: string): string {',
              '  const url = ART[name];',
              "  if (!url) throw new Error('unknown pack illustration: ' + name);",
              '  return url;',
              '}',
              '']
    out = os.path.join(APP_DIR, '..', 'frames.ts')
    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    print('png: %d, index + frames.ts scrise' % len(index))


def sheet():
    from PIL import Image
    names = all_names()
    cell, cols = 160, 5
    for page in range(3):
        batch = names[page * 25:(page + 1) * 25]
        out = Image.new('RGB', (cols * cell, 5 * cell), (24, 24, 28))
        for i, n in enumerate(batch):
            im = rasterize(n, cell - 8).convert('RGB')
            out.paste(im, ((i % cols) * cell + 4, (i // cols) * cell + 4))
        p = os.path.join(TMP, 'pack-p%d.png' % (page + 1))
        out.save(p)
        print('plansa:', p, len(batch), 'ilustratii')


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == 'sheet':
        sheet()
    elif len(sys.argv) > 1 and sys.argv[1] == 'app':
        app()
    else:
        print('folosire: raster-pack.py sheet|app')
