"""The live sprite sheet, as an Aseprite file with a tag per state.

`sheet.py` moves pixels between `frames.ts` and a PNG, which is enough to draw
in. This is the other half: it lays the sheet out as real Aseprite FRAMES, in
the order each state actually plays them, with a tag over each run. That is what
makes the animation tools work at all -- onion skin, tweening, playback, frame
diffing all address tags and frames, not a grid of unrelated cells.

    python sheet.py export        # frames-sheet.png + frames-sheet.json
    python to_aseprite.py         # writes to_aseprite.lua
    aseprite -b --script to_aseprite.lua

Or, from a session with the Aseprite MCP server, run the generated file with
`run_lua_script` and `dofile(...)`.

The result is one frame per entry in `VARIANTS`, so a state with three variants
of two frames each becomes three tags of two frames. Frames repeat where a
variant repeats them: a deliberate hold is part of the animation, not noise.

Frame duration is set to match `FRAME_MS` in `CinderpawMascot.tsx`. An animation
previewed at the wrong speed is a different animation.
"""
import io
import json
import re

OUT = '../../frontend-react/src/components/chat/mascot/'
SHEET = 'D:/Cinderpaw Agent/scripts/mascot/frames-sheet.png'
TARGET = 'D:/build/asetest/cinderpaw.aseprite'

src = io.open(OUT + 'frames.ts', encoding='utf-8').read()
ui = io.open(OUT + 'CinderpawMascot.tsx', encoding='utf-8').read()
meta = json.loads(io.open('frames-sheet.json', encoding='utf-8').read())

COLS = meta['cols']
W, H = meta['frame']
index = {n: i for i, n in enumerate(meta['names'])}
duration = int(re.search(r'const FRAME_MS = (\d+);', ui).group(1))

variants = re.search(r"export const VARIANTS[^=]*= \{(.*?)\n\};", src, re.S).group(1)
sequence, tags = [], []
for m in re.finditer(r"(\w+)\s*:\s*\[(.*)\],\s*$", variants, re.M):
    state = m.group(1)
    groups = re.findall(r"\[([^\[\]]+)\]", m.group(2))
    for i, group in enumerate(groups):
        start = len(sequence)
        sequence.extend(index[n.strip()] for n in group.split(',') if n.strip() in index)
        if len(sequence) > start:
            tags.append((state if len(groups) == 1 else '%s-%d' % (state, i + 1),
                         start, len(sequence) - 1))

lua = [
    '-- Generated by scripts/mascot/to_aseprite.py. Do not edit; regenerate.',
    '-- The sheet loads as pixels, never as an open sprite: app.open in batch',
    '-- mode leaves the session in a state where saveAs silently writes zero',
    '-- bytes (found the hard way, 2026-09-10).',
    'local src = Image{ fromFile = "%s" }' % SHEET,
    'local cell = {%s}' % ','.join(str(c) for c in sequence),
    'local W, H, COLS = %d, %d, %d' % (W, H, COLS),
    'local spr = Sprite(W, H)',
    'while #spr.frames < #cell do spr:newEmptyFrame() end',
    'for i, c in ipairs(cell) do',
    '  local img = Image(W, H)',
    '  local ox, oy = (c % COLS) * W, math.floor(c / COLS) * H',
    '  for y = 0, H - 1 do for x = 0, W - 1 do',
    '    img:drawPixel(x, y, src:getPixel(ox + x, oy + y))',
    '  end end',
    '  spr:newCel(spr.layers[1], i, img, Point(0, 0))',
    '  spr.frames[i].duration = %f' % (duration / 1000.0),
    'end',
]
for name, first, last in tags:
    lua.append('do local t = spr:newTag(%d, %d) t.name = "%s" end' % (first + 1, last + 1, name))
lua += [
    'spr:saveAs("%s")' % TARGET,
    'print("frames=" .. #spr.frames .. " tags=" .. #spr.tags)',
]

io.open('to_aseprite.lua', 'w', encoding='utf-8', newline='\n').write('\n'.join(lua) + '\n')
print('to_aseprite.lua : %d frames, %d tags, %dms each' % (len(sequence), len(tags), duration))
print('run it with:  aseprite -b --script to_aseprite.lua')
