//! Ollama-compatible HTTP API on port 11435.
//!
//! Security posture (V5 – hardened):
//!   - API server is **opt-in** (`api_server_enabled` defaults to `false`).
//!   - Bound to 127.0.0.1 only — never exposed to the LAN. A local inference
//!     server that also deletes model files has no business listening on
//!     0.0.0.0, where any device on the network could drive it.
//!   - Every route requires `Authorization: Bearer <token>`. The token is a
//!     per-launch random secret generated by the Tauri shell and shared with
//!     the legitimate consumers (the sidecar via the injected model api key,
//!     and external apps via `~/.feral/api-token`). This closes the
//!     same-host attack surface: other local processes and browser-based
//!     DNS-rebinding/CORS probes can reach the port but cannot use it.
//!   - `/api/delete` validates the model name as a bare filename and confirms
//!     containment inside the models directory before touching the disk, so a
//!     crafted `name` like `../../../../etc/passwd` can no longer escape it.
use axum::{
    extract::State,
    http::{header, HeaderValue, Request, StatusCode},
    middleware::{self, Next},
    response::sse::{Event, Sse},
    response::{IntoResponse, Response},
    routing::{delete, get, post},
    Json, Router,
};
use futures::stream::Stream;
use serde::Deserialize;
use serde_json::{json, Value};
use std::convert::Infallible;
use std::sync::atomic::AtomicBool;
use std::sync::Arc;
use tokio::sync::broadcast;
use tower_http::cors::{AllowOrigin, CorsLayer};

use crate::inference::{InferParams, Message, ModelManager};
use crate::models;
use crate::runtime::RuntimeState;

#[derive(Clone)]
pub struct ApiState {
    pub manager: Arc<ModelManager>,
        /// Per-launch random bearer token. Every request must present it as
    /// `Authorization: Bearer <token>`. Shared with the sidecar and external
    /// consumers out of band — see the module docstring.
    pub token: Arc<str>,
    /// Faza 4.5 Slice 3: the whole runtime, so the Public Runtime API
    /// `/runtime/*` endpoints report live status/inventory and `/events`
    /// subscribes to the observability bus. `manager`/`token` above stay as
    /// convenience handles the pre-Slice-3 handlers already read.
    pub runtime: Arc<RuntimeState>,
}

pub fn router(state: ApiState) -> Router {
    // CORS stays restricted to loopback origins. With bearer auth on top, a
    // malicious page that guesses the origin still cannot forge the token.
    let cors = CorsLayer::new()
        .allow_origin(AllowOrigin::predicate(|origin: &HeaderValue, _| {
            origin.as_bytes().starts_with(b"http://localhost")
                || origin.as_bytes().starts_with(b"http://127.0.0.1")
        }))
        .allow_methods(tower_http::cors::Any)
        .allow_headers(tower_http::cors::Any);

    Router::new()
        // Ollama-compatible
        .route("/api/tags", get(api_tags))
        .route("/api/show", post(api_show))
        .route("/api/generate", post(api_generate))
        .route("/api/chat", post(api_chat))
        .route("/api/delete", delete(api_delete))
        // OpenAI-compatible aliases
        .route("/v1/models", get(v1_models))
        .route("/v1/chat/completions", post(v1_chat_completions))
        // llama.cpp-server-compatible tokenizer (P3). The agent sidecar calls
        // this for accurate context accounting with the loaded model's real
        // vocabulary; its GPT-2 BPE fallback miscounts everything else.
        .route("/tokenize", post(api_tokenize))
        // Public Runtime API v1 (Faza 4.5 Slice 3, spec D3). Same posture as
        // the rest of this router: 127.0.0.1-only + bearer token. This first
        // vertical serves the Rust-local read-only surface + the `/events`
        // observability stream; the sidecar-round-trip endpoints
        // (/runtime/chat, /tools, /connectors, /memory, /dreams) land next.
        .route("/runtime/chat", post(runtime_chat))
        .route("/runtime/shutdown", post(runtime_shutdown))
        .route("/runtime/status", get(runtime_status))
        .route("/runtime/models", get(runtime_models))
        .route("/runtime/lora", get(runtime_lora))
        .route("/runtime/manifest", get(runtime_manifest))
        .route("/events", get(runtime_events))
        // Auth runs before any handler. `from_fn_with_state` hands the token
        // to the middleware so it can compare in constant time.
        .layer(middleware::from_fn_with_state(state.clone(), require_token))
        .with_state(state)
        .layer(cors)
}

/// Reject any request without a valid bearer token. CORS preflight
/// (`OPTIONS`) is allowed through so browsers can negotiate before the real
/// request carries the `Authorization` header.
async fn require_token(
    State(state): State<ApiState>,
    req: Request<axum::body::Body>,
    next: Next,
) -> Response {
    if req.method() == axum::http::Method::OPTIONS {
        return next.run(req).await;
    }
    let presented = req
        .headers()
        .get(header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.strip_prefix("Bearer "))
        .map(str::trim)
        .unwrap_or("");
    if constant_time_eq(presented.as_bytes(), state.token.as_bytes()) {
        next.run(req).await
    } else {
        (StatusCode::UNAUTHORIZED, "missing or invalid bearer token").into_response()
    }
}

/// Length-independent byte comparison. Localhost timing attacks are a stretch,
/// but a token check is exactly the place to not get cute — the cost is one
/// XOR per byte.
fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

pub async fn serve(state: ApiState, port: u16) -> anyhow::Result<()> {
    let app = router(state);
    // Loopback only — see module docstring. Binding to 0.0.0.0 here exposed
    // model deletion and inference to every host on the network.
    let addr = format!("127.0.0.1:{}", port);
    tracing::info!(%addr, "feral api listening (loopback, token-gated)");
    let listener = tokio::net::TcpListener::bind(&addr).await?;
    axum::serve(listener, app).await?;
    Ok(())
}

async fn api_tags() -> impl IntoResponse {
    let models = models::scan_models_dir().unwrap_or_default();
    let items: Vec<Value> = models.into_iter().map(|m| {
        json!({
            "name": m.name,
            "model": m.id,
            "size": m.size_bytes,
            "details": {
                "quantization_level": m.quant,
                "format": "gguf",
            }
        })
    }).collect();
    Json(json!({ "models": items }))
}

#[derive(Deserialize)]
struct ShowReq { name: String }

async fn api_show(Json(req): Json<ShowReq>) -> impl IntoResponse {
    let models = models::scan_models_dir().unwrap_or_default();
    match models.into_iter().find(|m| m.name == req.name || m.id == req.name) {
        Some(m) => Json(json!({
            "model": m.name,
            "size": m.size_bytes,
            "quant": m.quant,
            "modelfile": m.modelfile,
        })).into_response(),
        None => (StatusCode::NOT_FOUND, "not found").into_response(),
    }
}

#[derive(Deserialize)]
struct DeleteReq { name: String }

async fn api_delete(Json(req): Json<DeleteReq>) -> impl IntoResponse {
    let models_dir = crate::paths::models_dir();
    let path = match resolve_model_path_secure(&models_dir, &req.name) {
        Some(p) => p,
        None => return (StatusCode::BAD_REQUEST, "invalid or unsafe model name").into_response(),
    };
    match models::delete_model(&path) {
        Ok(_) => StatusCode::NO_CONTENT.into_response(),
        Err(e) => {
            tracing::warn!(path=%path.display(), error=%e, "api_delete failed");
            (StatusCode::NOT_FOUND, "model not found or could not be deleted").into_response()
        }
    }
}

/// Resolve a caller-supplied model name to a path inside `models_dir`, or
/// `None` if the name is not a safe, contained filename.
///
/// Three layers of defense:
///   1. Reject anything that isn't a bare filename — empty, containing a path
///      separator, a `..` component, or an absolute/rooted path. This blocks
///      the obvious `../../etc/passwd` and `C:\Windows\...` shapes before any
///      filesystem call.
///   2. Confirm the joined path's parent canonicalizes to the models
///      directory. This catches anything the first check missed (symlinks,
///      platform-specific quirks) by comparing real on-disk locations.
///   3. After canonicalizing the *final* path, verify it still starts with
///      the canonical models directory. This defends against TOCTOU races
///      and symlink tricks that swap targets between the parent check and
///      the actual operation.
fn resolve_model_path_secure(models_dir: &std::path::Path, name: &str) -> Option<std::path::PathBuf> {
    let name = name.trim();
    if name.is_empty() {
        return None;
    }
    let candidate = std::path::Path::new(name);
    // Must be exactly one normal path component (the filename itself).
    let mut comps = candidate.components();
    let only = match (comps.next(), comps.next()) {
        (Some(std::path::Component::Normal(c)), None) => c,
        _ => return None,
    };
    if only != std::ffi::OsStr::new(name) {
        return None;
    }
    // Canonicalize the models directory; if it doesn't exist there's nothing to delete.
    let real_dir = models_dir.canonicalize().ok()?;
    let path = models_dir.join(only);
    // Containment check #1: the parent of the candidate must *be* the real models dir.
    let real_parent = path.parent()?.canonicalize().ok()?;
    if real_parent != real_dir {
        return None;
    }
    // Containment check #2 (defense in depth): if the file itself exists,
    // its canonical path must still start with the real models directory.
    if let Ok(real_path) = path.canonicalize() {
        if !real_path.starts_with(&real_dir) {
            return None;
        }
    }
    Some(path)
}

#[derive(Deserialize)]
struct GenerateReq {
    model: String,
    prompt: String,
    #[serde(default)]
    stream: Option<bool>,
    #[serde(default)]
    options: Option<Value>,
    #[serde(default)]
    max_tokens: Option<u32>,
}

async fn api_generate(
    State(state): State<ApiState>,
    Json(req): Json<GenerateReq>,
) -> impl IntoResponse {
    let messages = vec![Message { role: "user".into(), content: req.prompt, images: None }];
    let mut params = params_from_options(req.options.as_ref());
    apply_max_tokens(&mut params, req.max_tokens);

    if req.stream.unwrap_or(true) {
        sse_from_chat(state, req.model, messages, params, false).into_response()
    } else {
        let text = collect_chat(&state, messages, params).await;
        Json(json!({
            "model": req.model,
            "response": text,
            "done": true,
        })).into_response()
    }
}

/// OpenAI-compatible message content: either a plain string or an array of
/// content parts (`[{ "type": "text", "text": "..." }, ...]`). OpenAI-spec
/// clients send the array form; llama.cpp only needs the text.
#[derive(Deserialize)]
#[serde(untagged)]
enum FlexContent {
    Text(String),
    Parts(Vec<ContentPart>),
}

#[derive(Deserialize)]
struct ContentPart {
    #[serde(default)]
    text: Option<String>,
}

impl FlexContent {
    /// Flatten to a single string. Array parts are concatenated; non-text
    /// parts (images, etc.) contribute nothing since llama.cpp is text-only.
    fn into_string(self) -> String {
        match self {
            FlexContent::Text(s) => s,
            FlexContent::Parts(parts) => parts
                .into_iter()
                .filter_map(|p| p.text)
                .collect::<Vec<_>>()
                .join(""),
        }
    }
}

#[derive(Deserialize)]
struct ApiMessage {
    role: String,
    #[serde(default)]
    content: Option<FlexContent>,
}

impl From<ApiMessage> for Message {
    fn from(m: ApiMessage) -> Self {
        Message {
            role: m.role,
            content: m.content.map(FlexContent::into_string).unwrap_or_default(),
            images: None,
        }
    }
}

#[derive(Deserialize)]
struct ChatReq {
    model: String,
    messages: Vec<ApiMessage>,
    #[serde(default)]
    stream: Option<bool>,
    #[serde(default)]
    options: Option<Value>,
    /// OpenAI-standard generation cap. OpenAI-spec clients send this at the
    /// top level (not nested under `options`). Without honoring it, every
    /// agent request fell back to the 1024-token default and ran for
    /// minutes of CPU inference, appearing to hang.
    #[serde(default)]
    max_tokens: Option<u32>,
    /// Feral extension: a GBNF grammar that constrains decoding. The agent
    /// sidecar sends this to force valid tool-call JSON (grammar-constrained
    /// decoding). Standard OpenAI clients omit it and get unconstrained output.
    #[serde(default)]
    grammar: Option<String>,
    /// Feral extension: trigger strings for lazy grammar enforcement (see
    /// `InferParams::grammar_triggers`). The grammar engages only after one of
    /// these appears, so prose stays unconstrained and only the tool call is.
    #[serde(default)]
    grammar_triggers: Option<Vec<String>>,
    /// Feral extension (P1 — prompt caching): caller-supplied session id
    /// threaded into the audit log so a row can be cross-referenced with
    /// what the user saw. The bundled llama.cpp engine draws contexts from
    /// a small pool (P6); each context keeps its own KV prefix-diff record,
    /// and reuse is opportunistic — a caller that lands on a context whose
    /// cache shares its prefix benefits, regardless of session id. The
    /// field is plumbed through now so a future session→context affinity
    /// strategy can be added without another breaking schema change.
    #[serde(default)]
    session_id: Option<String>,
}

impl ChatReq {
    /// Convert incoming OpenAI-style messages into Feral's internal `Message`.
    fn into_messages(self) -> Vec<Message> {
        self.messages.into_iter().map(Message::from).collect()
    }
}

/// One lazy-load at a time — a burst of eval requests must not stack up N
/// concurrent `manager.load` calls for the same model.
static API_AUTOLOAD_IN_FLIGHT: std::sync::atomic::AtomicBool =
    std::sync::atomic::AtomicBool::new(false);

/// Ensure a model is loaded before serving a completion.
///
/// Boot auto-load was deliberately removed (2026-06-30: mmap lag froze
/// non-technical users' machines), so nothing guarantees a loaded model when
/// an API caller arrives — the RSI Dream Cycle's first episode burned every
/// eval on "no model loaded", and connectors hit the same hole whenever the
/// user hadn't touched the Local Models tab. The fix that respects the
/// no-boot-load decision: load lazily HERE, on first demand, using the model
/// id the caller asked for (falling back to the first model on disk). Waits
/// out a concurrent load (UI or another request) up to `FERAL_MODEL_WAIT_MS`
/// (default 120s).
async fn wait_for_model(state: &ApiState, requested: &str) -> bool {
    use std::sync::atomic::Ordering;
    if state.manager.current().is_some() {
        return true;
    }

    if !API_AUTOLOAD_IN_FLIGHT.swap(true, Ordering::SeqCst) {
        // We own the load. Resolve the requested id against the models dir.
        let requested = requested.to_string();
        let manager = state.manager.clone();
        let loaded = tokio::task::spawn_blocking(move || {
            let models = models::scan_models_dir().unwrap_or_default();
            let pick = models
                .iter()
                .find(|m| m.id == requested || m.name == requested)
                .or_else(|| models.first());
            match pick {
                Some(m) => {
                    tracing::info!(model = %m.id, "api: lazy-loading model on first completion request");
                    // n_gpu_layers -1 = offload all (GPU builds fall back to
                    // CPU internally); context uses the conservative default
                    // cap — the UI's Hardware choice re-applies on its next
                    // explicit load.
                    manager.load(m.path.clone(), -1, None).map(|_| true).unwrap_or(false)
                }
                None => false,
            }
        })
        .await
        .unwrap_or(false);
        API_AUTOLOAD_IN_FLIGHT.store(false, Ordering::SeqCst);
        if loaded {
            return true;
        }
        // Fall through to the wait loop — a concurrent UI load may still land.
    }

    let deadline_ms = std::env::var("FERAL_MODEL_WAIT_MS")
        .ok()
        .and_then(|v| v.trim().parse::<u64>().ok())
        .unwrap_or(120_000);
    let start = std::time::Instant::now();
    while start.elapsed().as_millis() < u128::from(deadline_ms) {
        if state.manager.current().is_some() {
            return true;
        }
        if !API_AUTOLOAD_IN_FLIGHT.load(Ordering::SeqCst) {
            // No load in flight anymore and still no model → nothing on disk
            // or the load failed; give the caller a real error now.
            if state.manager.current().is_none() {
                return false;
            }
        }
        tokio::time::sleep(std::time::Duration::from_millis(500)).await;
    }
    false
}

/// The 503 body both chat endpoints return when `wait_for_model` gives up.
/// A real status code (not an empty 200) lets the sidecar's router treat it
/// as a failed call it can surface, instead of a silent empty response.
fn no_model_response() -> axum::response::Response {
    (
        StatusCode::SERVICE_UNAVAILABLE,
        Json(json!({ "error": { "message": "no model loaded", "type": "model_not_ready" } })),
    )
        .into_response()
}

async fn api_chat(
    State(state): State<ApiState>,
    Json(req): Json<ChatReq>,
) -> impl IntoResponse {
    if !wait_for_model(&state, &req.model).await {
        return no_model_response();
    }
    let mut params = params_from_options(req.options.as_ref());
    apply_max_tokens(&mut params, req.max_tokens);
    apply_grammar(&mut params, &req);
    apply_session(&mut params, &req);
    let model = req.model.clone();
    let stream = req.stream.unwrap_or(true);
    let messages = req.into_messages();
    if stream {
        sse_from_chat(state, model, messages, params, false).into_response()
    } else {
        let text = collect_chat(&state, messages, params).await;
        Json(json!({
            "model": model,
            "message": { "role": "assistant", "content": text },
            "done": true,
        })).into_response()
    }
}

#[derive(Deserialize)]
struct TokenizeReq {
    content: String,
    /// Accepted for llama.cpp-server compatibility; tokenization always uses
    /// the currently loaded model.
    #[serde(default)]
    #[allow(dead_code)]
    model: Option<String>,
}

/// Count tokens with the loaded model's tokenizer. Returns `{"count": n}` —
/// the sidecar's `tokenizeLocal()` accepts either a `tokens` array or a
/// `count`; sending only the count avoids serializing thousands of ids for
/// long prompts.
async fn api_tokenize(
    State(state): State<ApiState>,
    Json(req): Json<TokenizeReq>,
) -> impl IntoResponse {
    match state.manager.count_tokens(&req.content) {
        Ok(n) => Json(json!({ "count": n })).into_response(),
        Err(e) => (StatusCode::SERVICE_UNAVAILABLE, e.to_string()).into_response(),
    }
}

async fn v1_models() -> impl IntoResponse {
    let models = models::scan_models_dir().unwrap_or_default();
    let data: Vec<Value> = models.into_iter().map(|m| {
        json!({ "id": m.id, "object": "model", "owned_by": "feral" })
    }).collect();
    Json(json!({ "object": "list", "data": data }))
}

// ── Public Runtime API v1 (Faza 4.5 Slice 3) ──────────────────────────────
//
// All handlers here read from `state.runtime` (the host-agnostic RuntimeState)
// so every host — desktop or headless gateway — serves identical answers
// (invariant 11). Nothing here fabricates: fields the runtime cannot source
// locally (connectors/memories/dreams live in the sidecar) are reported as
// `null` until the sidecar-round-trip vertical wires them.

#[derive(Deserialize)]
struct RuntimeChatReq {
    /// The user's new message. The sidecar owns per-session history (unified
    /// memory, invariant 11), so we forward only the new turn, not a transcript.
    content: String,
    /// Session key. Every client that shares a `session_id` shares one
    /// conversation + memory. Defaults to `api` per spec D3.
    #[serde(default = "default_session")]
    session_id: String,
    /// SSE token stream (default) vs a single JSON reply.
    #[serde(default = "default_true")]
    stream: bool,
}
fn default_session() -> String { "api".to_string() }
fn default_true() -> bool { true }

/// How long to wait for the next reply fragment before giving up. Local
/// inference plus a tool call can be slow; 120s idle is generous without
/// hanging a dead sidecar's socket open forever.
const CHAT_IDLE_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(120);

/// D3: forward a chat turn to the supervised sidecar and stream the reply.
///
/// The sidecar broadcasts *all* output on one bus as `feral://agent-output`
/// events (no per-request socket), so we correlate our reply by the message
/// `id` we generate: subscribe to the bus BEFORE sending (no lost-first-token
/// race), send `{"type":"message", id, content, sessionId}`, then keep only
/// `chunk`/`done` events whose `id` matches ours. Same session, same memory,
/// same LoRA, same tools as the desktop and the connectors — this is just
/// another face on the one brain.
async fn runtime_chat(
    State(state): State<ApiState>,
    Json(req): Json<RuntimeChatReq>,
) -> Response {
    let rt = &state.runtime;

    // Grab the sidecar sender without holding the lock across the await.
    let tx = {
        let guard = rt.feral_agent_tx.lock();
        match guard.as_ref() {
            Some(tx) => tx.clone(),
            None => {
                return (StatusCode::SERVICE_UNAVAILABLE, "feral-agent sidecar is not running")
                    .into_response()
            }
        }
    };

    let msg_id = uuid::Uuid::new_v4().to_string();
    // Subscribe BEFORE sending so we can't miss the first chunk.
    let rx = rt.events_tx.subscribe();

    let outbound = json!({
        "type": "message",
        "id": msg_id,
        "content": req.content,
        "sessionId": req.session_id,
    })
    .to_string();
    if tx.send(outbound).await.is_err() {
        return (StatusCode::SERVICE_UNAVAILABLE, "feral-agent sidecar stopped accepting messages")
            .into_response();
    }

    if req.stream {
        sse_from_agent_reply(rx, msg_id).into_response()
    } else {
        // Non-stream: the `done` event already carries the full text, so we
        // just wait for our matching `done` instead of accumulating chunks.
        match await_agent_reply(rx, &msg_id).await {
            Ok(text) => Json(json!({
                "id": msg_id,
                "session_id": req.session_id,
                "content": text,
            }))
            .into_response(),
            Err(e) => (StatusCode::GATEWAY_TIMEOUT, e).into_response(),
        }
    }
}

/// Pull one line's `type`+`id`+`content` out of a `feral://agent-output`
/// broadcast event, if it is one. The payload is `{"data": "<json line>"}`
/// where the line is itself the sidecar's JSON event.
fn parse_agent_output(ev: &crate::host::HostEvent) -> Option<(String, String, String)> {
    if ev.event != "feral://agent-output" {
        return None;
    }
    let line = ev.payload.get("data")?.as_str()?;
    let v: Value = serde_json::from_str(line).ok()?;
    let ty = v.get("type")?.as_str()?.to_string();
    let id = v.get("id").and_then(|x| x.as_str()).unwrap_or("").to_string();
    // `chunk`/`done` carry the text in `content`; `error` carries it in
    // `message`. Fall back so the correlator can surface failures too.
    let content = v
        .get("content")
        .and_then(|x| x.as_str())
        .or_else(|| v.get("message").and_then(|x| x.as_str()))
        .unwrap_or("")
        .to_string();
    Some((ty, id, content))
}

/// Wait for the `done` event matching `msg_id`, returning its full text.
/// Used by the non-stream path.
async fn await_agent_reply(
    mut rx: broadcast::Receiver<crate::host::HostEvent>,
    msg_id: &str,
) -> Result<String, String> {
    loop {
        match tokio::time::timeout(CHAT_IDLE_TIMEOUT, rx.recv()).await {
            Ok(Ok(ev)) => {
                if let Some((ty, id, content)) = parse_agent_output(&ev) {
                    if id == msg_id {
                        match ty.as_str() {
                            "done" => return Ok(content),
                            "error" => return Err(format!("sidecar inference error: {content}")),
                            _ => {}
                        }
                    }
                }
            }
            Ok(Err(broadcast::error::RecvError::Lagged(_))) => continue,
            Ok(Err(broadcast::error::RecvError::Closed)) => {
                return Err("runtime event bus closed before reply completed".into())
            }
            Err(_) => return Err("timed out waiting for sidecar reply".into()),
        }
    }
}

/// SSE the reply for `msg_id` as OpenAI-style chat chunks (so any OpenAI SSE
/// client — and `feral chat` — can consume it), terminating with `[DONE]`.
fn sse_from_agent_reply(
    rx: broadcast::Receiver<crate::host::HostEvent>,
    msg_id: String,
) -> Sse<impl Stream<Item = Result<Event, Infallible>>> {
    use async_stream::stream;
    let s = stream! {
        let mut rx = rx;
        loop {
            let recv = tokio::time::timeout(CHAT_IDLE_TIMEOUT, rx.recv()).await;
            match recv {
                Ok(Ok(ev)) => {
                    let Some((ty, id, content)) = parse_agent_output(&ev) else { continue };
                    if id != msg_id { continue; }
                    match ty.as_str() {
                        "chunk" => {
                            let payload = json!({
                                "id": format!("chatcmpl-{msg_id}"),
                                "object": "chat.completion.chunk",
                                "choices": [{ "index": 0, "delta": { "content": content } }],
                            });
                            yield Ok::<_, Infallible>(Event::default().data(payload.to_string()));
                        }
                        "done" => {
                            let payload = json!({
                                "id": format!("chatcmpl-{msg_id}"),
                                "object": "chat.completion.chunk",
                                "choices": [{ "index": 0, "delta": {}, "finish_reason": "stop" }],
                            });
                            yield Ok(Event::default().data(payload.to_string()));
                            yield Ok(Event::default().data("[DONE]"));
                            break;
                        }
                        "error" => {
                            // Surface the sidecar's inference error to the client
                            // instead of hanging until the idle timeout.
                            tracing::warn!(msg_id = %msg_id, error = %content, "/runtime/chat sidecar error");
                            let payload = json!({
                                "id": format!("chatcmpl-{msg_id}"),
                                "object": "chat.completion.chunk",
                                "choices": [{ "index": 0, "delta": {}, "finish_reason": "error" }],
                                "error": content,
                            });
                            yield Ok(Event::default().data(payload.to_string()));
                            yield Ok(Event::default().data("[DONE]"));
                            break;
                        }
                        _ => {} // tool_done / usage / etc. — not part of the text stream
                    }
                }
                Ok(Err(broadcast::error::RecvError::Lagged(n))) => {
                    tracing::warn!(skipped = n, "/runtime/chat subscriber lagged");
                    continue;
                }
                Ok(Err(broadcast::error::RecvError::Closed)) => break,
                Err(_) => {
                    // Idle timeout — close the stream rather than hang.
                    tracing::warn!(msg_id = %msg_id, "/runtime/chat idle timeout");
                    yield Ok(Event::default().data("[DONE]"));
                    break;
                }
            }
        }
    };
    Sse::new(s)
}

/// Slice 4: request a graceful shutdown. Fires the runtime's shutdown signal;
/// the headless gateway's main loop wakes and runs the D7 drain. Token-gated +
/// loopback like everything else — a local holder of the token could already
/// drive inference and delete models, so letting it stop the daemon is no new
/// exposure. `feral gateway stop` calls this (no Windows signal games).
async fn runtime_shutdown(State(state): State<ApiState>) -> impl IntoResponse {
    tracing::info!("runtime: shutdown requested via /runtime/shutdown");
    state.runtime.shutdown.notify_waiters();
    // notify_one() as well, so a request that races ahead of the gateway's
    // `.notified()` still lands (stores a permit); notify_waiters alone would
    // be lost if no task is parked yet.
    state.runtime.shutdown.notify_one();
    Json(json!({ "ok": true, "shutting_down": true }))
}

/// D3: loaded model, active LoRA, sidecar liveness, backend, RSI engine mirror.
async fn runtime_status(State(state): State<ApiState>) -> impl IntoResponse {
    let rt = &state.runtime;
    let model = rt.manager.current().map(|m| {
        json!({ "name": m.name, "ctx_len": m.ctx_len, "n_ctx_train": m.n_ctx_train })
    });
    let sidecar_alive = rt.feral_agent_process.lock().is_some();
    let rsi_engine = rt.rsi_engine.lock().clone().map(|e| {
        json!({
            "running": e.running,
            "iteration": e.iteration,
            "best_score": e.best_score,
            "cost_so_far_usd": e.cost_so_far_usd,
            "concurrency": e.concurrency,
        })
    });
    Json(json!({
        "model": model,
        // What the sidecar actually infers with (local GGUF name or a cloud
        // model id). For a cloud session `model` above is null but this is set.
        "agent_model": rt.active_agent_model.lock().clone(),
        "lora": crate::inference::active_lora_adapter(),
        "sidecar_alive": sidecar_alive,
        "backend": crate::inference::active_backend_label(),
        "gpu": crate::inference::gpu_active(),
        "rsi_engine": rsi_engine,
    }))
}

/// D3: model inventory on disk + which one is loaded. `active` is the loaded
/// model's internal name; the inventory `id`s are the on-disk identifiers. We
/// return both rather than joining them — the two namespaces are not guaranteed
/// equal, and a wrong per-item `active` flag is worse than none.
async fn runtime_models(State(state): State<ApiState>) -> impl IntoResponse {
    let active = state.runtime.manager.current().map(|m| m.name);
    let models = models::scan_models_dir().unwrap_or_default();
    let ids: Vec<String> = models.into_iter().map(|m| m.id).collect();
    Json(json!({ "models": ids, "active": active }))
}

/// D3: the active LoRA adapter. Full adapter inventory is deferred — no disk
/// scanner is surfaced from feral-core yet, and reporting a fabricated list
/// would be worse than reporting only what is provably active.
async fn runtime_lora() -> impl IntoResponse {
    Json(json!({ "active": crate::inference::active_lora_adapter() }))
}

/// D3b: declarative runtime snapshot. The foundation for `feral export` /
/// `feral import` (a future phase — v1 is read-only). Locally-sourced keys are
/// filled; sidecar-sourced keys (connectors/memories/dreams) are `null` until
/// the sidecar-round-trip vertical wires them, so a client can tell the
/// difference between "empty" and "not yet available".
async fn runtime_manifest(State(state): State<ApiState>) -> impl IntoResponse {
    let rt = &state.runtime;
    let active_model = rt.manager.current().map(|m| m.name);
    let models: Vec<String> = models::scan_models_dir()
        .unwrap_or_default()
        .into_iter()
        .map(|m| m.id)
        .collect();
    Json(json!({
        "version": env!("CARGO_PKG_VERSION"),
        "models": models,
        "active_model": active_model,
        "agent_model": rt.active_agent_model.lock().clone(),
        "loras": { "active": crate::inference::active_lora_adapter() },
        "providers": {
            "backend": crate::inference::active_backend_label(),
            "gpu": crate::inference::gpu_active(),
        },
        "connectors": Value::Null,
        "memories": Value::Null,
        "dreams": Value::Null,
    }))
}

/// D3: unified observability stream. Subscribes to the runtime's broadcast bus
/// (fed by any `BroadcastEvents` sink) and replays every host event as SSE.
/// The headless gateway wires `BroadcastEvents`; on the desktop host today the
/// bus is idle (TauriEvents forwards to the webview) — uniform `/events` on
/// desktop is a Faza 5 concern. `curl -N /events` proves it live.
async fn runtime_events(
    State(state): State<ApiState>,
) -> Sse<impl Stream<Item = Result<Event, Infallible>>> {
    use async_stream::stream;
    let mut rx = state.runtime.events_tx.subscribe();
    let s = stream! {
        loop {
            match rx.recv().await {
                Ok(ev) => {
                    let data = json!({ "event": ev.event, "data": ev.payload }).to_string();
                    yield Ok::<_, Infallible>(Event::default().event("runtime").data(data));
                }
                // A subscriber that fell behind the 512-event ring lost `n`
                // events. Log it and keep streaming from the current tail
                // rather than tearing the connection down.
                Err(broadcast::error::RecvError::Lagged(n)) => {
                    tracing::warn!(skipped = n, "/events subscriber lagged");
                    continue;
                }
                Err(broadcast::error::RecvError::Closed) => break,
            }
        }
    };
    Sse::new(s)
}

async fn v1_chat_completions(
    State(state): State<ApiState>,
    Json(req): Json<ChatReq>,
) -> impl IntoResponse {
    if !wait_for_model(&state, &req.model).await {
        return no_model_response();
    }
    let mut params = params_from_options(req.options.as_ref());
    apply_max_tokens(&mut params, req.max_tokens);
    apply_grammar(&mut params, &req);
    apply_session(&mut params, &req);
    let model = req.model.clone();
    let stream = req.stream.unwrap_or(false);
    let messages = req.into_messages();
    if stream {
        sse_from_chat(state, model, messages, params, true).into_response()
    } else {
        let text = collect_chat(&state, messages, params).await;
        Json(json!({
            "id": format!("chatcmpl-{}", uuid::Uuid::new_v4()),
            "object": "chat.completion",
            "model": model,
            "choices": [{
                "index": 0,
                "message": { "role": "assistant", "content": text },
                "finish_reason": "stop",
            }],
        })).into_response()
    }
}

/// Apply the OpenAI-standard top-level `max_tokens` over whatever
/// `params_from_options` produced. A request that explicitly asks for fewer
/// tokens must win over the 1024-token default; `0` is ignored as a no-op.
fn apply_max_tokens(params: &mut InferParams, max_tokens: Option<u32>) {
    if let Some(mt) = max_tokens {
        if mt > 0 {
            params.max_tokens = mt;
        }
    }
}

/// Copy the Feral grammar extension fields from the request onto the inference
/// params. A no-op for standard OpenAI clients (both fields default to None).
fn apply_grammar(params: &mut InferParams, req: &ChatReq) {
    params.grammar = req.grammar.clone();
    params.grammar_triggers = req.grammar_triggers.clone();
}

/// P1 (prompt caching): copy the Feral session-id extension from the request
/// onto the inference params. Currently used for audit/logging only —
/// contexts come from the P6 pool with no session→context affinity yet. The
/// field is plumbed here so a future affinity strategy (or per-session
/// telemetry) can be added without another breaking schema change on the API.
fn apply_session(params: &mut InferParams, req: &ChatReq) {
    params.session_id = req.session_id.clone();
}

fn params_from_options(opts: Option<&Value>) -> InferParams {
    let mut p = InferParams::default();
    if let Some(o) = opts {
        if let Some(v) = o.get("temperature").and_then(|v| v.as_f64()) { p.temperature = v as f32; }
        if let Some(v) = o.get("top_p").and_then(|v| v.as_f64()) { p.top_p = v as f32; }
        if let Some(v) = o.get("repeat_penalty").and_then(|v| v.as_f64()) { p.repeat_penalty = v as f32; }
        if let Some(v) = o.get("num_predict").and_then(|v| v.as_u64()) { p.max_tokens = v as u32; }
    }
    p
}

async fn collect_chat(state: &ApiState, messages: Vec<Message>, params: InferParams) -> String {
    use futures::StreamExt;
    let stop = Arc::new(AtomicBool::new(false));
    let mut out = String::new();
    let mut stream = Box::pin(state.manager.stream_chat(messages, params, stop, None));
    while let Some(tok) = stream.next().await {
        match tok {
            Ok(t) => out.push_str(&t),
            Err(e) => { tracing::warn!("token error: {}", e); break; }
        }
    }
    out
}

fn sse_from_chat(
    state: ApiState,
    model: String,
    messages: Vec<Message>,
    params: InferParams,
    openai_format: bool,
) -> Sse<impl Stream<Item = Result<Event, Infallible>>> {
    use async_stream::stream;
    use futures::StreamExt;

    let s = stream! {
        let stop = Arc::new(AtomicBool::new(false));
        let mut chat = Box::pin(state.manager.stream_chat(messages, params, stop, None));
        while let Some(tok) = chat.next().await {
            let t = match tok { Ok(t) => t, Err(e) => { tracing::warn!("sse token error: {}", e); break; } };
            let payload = if openai_format {
                json!({
                    "id": "chatcmpl-stream",
                    "object": "chat.completion.chunk",
                    "model": model,
                    "choices": [{ "index": 0, "delta": { "content": t } }],
                })
            } else {
                json!({
                    "model": model,
                    "message": { "role": "assistant", "content": t },
                    "done": false,
                })
            };
            yield Ok::<_, Infallible>(Event::default().data(payload.to_string()));
        }
        let done = if openai_format {
            json!({
                "id": "chatcmpl-stream",
                "object": "chat.completion.chunk",
                "model": model,
                "choices": [{ "index": 0, "delta": {}, "finish_reason": "stop" }],
            })
        } else {
            json!({ "model": model, "done": true })
        };
        yield Ok(Event::default().data(done.to_string()));

        // OpenAI streaming protocol terminates with `data: [DONE]`. The
        // SSE parser waits for this sentinel — without it the stream is treated
        // as an incomplete terminal response.
        if openai_format {
            yield Ok(Event::default().data("[DONE]"));
        }
    };
    Sse::new(s)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::host::HostEvent;

    fn agent_output(line: &str) -> HostEvent {
        HostEvent { event: "feral://agent-output".into(), payload: json!({ "data": line }) }
    }

    #[test]
    fn parse_agent_output_extracts_chunk() {
        let ev = agent_output(r#"{"type":"chunk","id":"abc","content":"hel"}"#);
        assert_eq!(
            parse_agent_output(&ev),
            Some(("chunk".into(), "abc".into(), "hel".into()))
        );
    }

    #[test]
    fn parse_agent_output_done_carries_full_text() {
        let ev = agent_output(r#"{"type":"done","id":"abc","content":"hello","stopped":false}"#);
        assert_eq!(
            parse_agent_output(&ev),
            Some(("done".into(), "abc".into(), "hello".into()))
        );
    }

    #[test]
    fn parse_agent_output_ignores_non_agent_events() {
        let ev = HostEvent { event: "feral://agent-ready".into(), payload: json!({}) };
        assert_eq!(parse_agent_output(&ev), None);
    }

    #[test]
    fn parse_agent_output_ignores_unparseable_data() {
        // A log line that isn't JSON must not crash the correlator.
        assert_eq!(parse_agent_output(&agent_output("not json")), None);
    }
}
