//! Ollama-compatible HTTP API on port 11435.
//!
//! Security posture (V5 – hardened):
//!   - API server is **opt-in** (`api_server_enabled` defaults to `false`).
//!   - Bound to 127.0.0.1 only — never exposed to the LAN. A local inference
//!     server that also deletes model files has no business listening on
//!     0.0.0.0, where any device on the network could drive it.
//!   - Every route requires `Authorization: Bearer <token>`. The token is a
//!     per-launch random secret generated by the Tauri shell and shared with
//!     the legitimate consumers (the sidecar via the injected model api key,
//!     and external apps via `~/.feral/api-token`). This closes the
//!     same-host attack surface: other local processes and browser-based
//!     DNS-rebinding/CORS probes can reach the port but cannot use it.
//!   - `/api/delete` validates the model name as a bare filename and confirms
//!     containment inside the models directory before touching the disk, so a
//!     crafted `name` like `../../../../etc/passwd` can no longer escape it.
use axum::{
    extract::{Query, State},
    http::{header, HeaderMap, HeaderName, HeaderValue, Request, StatusCode},
    middleware::{self, Next},
    response::sse::{Event, Sse},
    response::{IntoResponse, Response},
    routing::{delete, get, post},
    Json, Router,
};
use futures::stream::Stream;
use serde::Deserialize;
use serde_json::{json, Value};
use std::convert::Infallible;
use std::sync::atomic::AtomicBool;
use std::sync::Arc;
use tokio::sync::broadcast;
use tower_http::cors::{AllowOrigin, CorsLayer};

use crate::byok;
use crate::connectors as connector_catalog;
use crate::inference::{InferParams, Message, ModelManager};
use crate::models;
use crate::runtime::RuntimeState;

#[derive(Clone)]
pub struct ApiState {
    pub manager: Arc<ModelManager>,
        /// Per-launch random bearer token. Every request must present it as
    /// `Authorization: Bearer <token>`. Shared with the sidecar and external
    /// consumers out of band — see the module docstring.
    pub token: Arc<str>,
    /// Faza 4.5 Slice 3: the whole runtime, so the Public Runtime API
    /// `/runtime/*` endpoints report live status/inventory and `/events`
    /// subscribes to the observability bus. `manager`/`token` above stay as
    /// convenience handles the pre-Slice-3 handlers already read.
    pub runtime: Arc<RuntimeState>,
}

pub fn router(state: ApiState) -> Router {
    // CORS stays restricted to loopback origins. With bearer auth on top, a
    // malicious page that guesses the origin still cannot forge the token.
    let cors = CorsLayer::new()
        .allow_origin(AllowOrigin::predicate(|origin: &HeaderValue, _| {
            origin.as_bytes().starts_with(b"http://localhost")
                || origin.as_bytes().starts_with(b"http://127.0.0.1")
        }))
        .allow_methods(tower_http::cors::Any)
        .allow_headers(tower_http::cors::Any);

    Router::new()
        // Ollama-compatible
        .route("/api/tags", get(api_tags))
        .route("/api/show", post(api_show))
        .route("/api/generate", post(api_generate))
        .route("/api/chat", post(api_chat))
        .route("/api/delete", delete(api_delete))
        // OpenAI-compatible aliases
        .route("/v1/models", get(v1_models))
        .route("/v1/chat/completions", post(v1_chat_completions))
        // llama.cpp-server-compatible tokenizer (P3). The agent sidecar calls
        // this for accurate context accounting with the loaded model's real
        // vocabulary; its GPT-2 BPE fallback miscounts everything else.
        .route("/tokenize", post(api_tokenize))
        // Public Runtime API v1 (Faza 4.5 Slice 3, spec D3). Same posture as
        // the rest of this router: 127.0.0.1-only + bearer token. This first
        // vertical serves the Rust-local read-only surface + the `/events`
        // observability stream; the sidecar-round-trip endpoints
        // (/runtime/chat, /tools, /connectors, /memory, /dreams) land next.
        .route("/runtime/chat", post(runtime_chat))
        .route("/runtime/connectors/reload", post(runtime_connectors_reload))
        .route("/runtime/shutdown", post(runtime_shutdown))
        .route("/runtime/status", get(runtime_status))
        .route("/runtime/models", get(runtime_models))
        .route("/runtime/model", post(runtime_set_model))
        .route("/runtime/lora", get(runtime_lora))
        .route("/runtime/manifest", get(runtime_manifest))
        .route("/runtime/sessions", get(runtime_sessions))
        // Sprint 1.6 — Memory Resume. Headless / TUI clients hit this; the
        // desktop Tauri app uses the `get_last_task` command which delegates
        // to the same sidecar roundtrip but stays in-process. Same shape:
        // subscribe-before-send, wait for `resume_get_result`.
        .route("/runtime/resume", get(runtime_resume))
        // Sprint 2 / audit C-1 — hardware probe for the TUI Setup Wizard.
        // Same shape as the Tauri command `get_system_info`. The wizard used
        // to hard-code "rtx 4070 · 12 GB" on every machine; now it reads
        // the real GPU/VRAM/RAM/disk via sysinfo_mod::detect().
        .route("/system_info", get(system_info))
        // Sprint 2 / audit C-2 — real provider key validation for the wizard.
        // Body: `{ provider_id, api_key, base_url? }`. Returns the provider's
        // real status text — "401 Unauthorized", "Invalid API key", etc. —
        // so the wizard can surface the actual reason instead of a fake ✓.
        .route("/providers/test", post(providers_test))
        // Phase 0b (2026-07-07, terminal-onboarding slice) — persist a
        // provider's API key to the OS keychain and its metadata to
        // `~/.feral/byok.json`. Body: `{ provider_id, enabled, api_key,
        // base_url?, default_model? }`. Empty `api_key` leaves the keychain
        // entry untouched (matches the existing `byok::save` semantics). The
        // response never echoes the key. Closes the silent key-drop bug
        // where the headless wizard validated a freshly-entered key against
        // `/providers/test` but never persisted it to the keychain, so the
        // next launch reported "No API key configured".
        .route("/runtime/byok/save", post(runtime_byok_save))
        // Sprint 2 / audit C-5 — real model download with progress.
        // POST kicks off a background download and returns a download id;
        // GET on the same id returns the latest progress + status.
        // The TUI Setup Wizard polls the GET route every 500ms.
        .route("/runtime/models/install", post(runtime_models_install))
        .route("/runtime/models/download/:id", get(runtime_models_download))
        // Faza 6 (L6) Meta Evolution — sidecar round-trips correlated by id.
        // `/meta/evaluate` is an alias of `/meta/current`: the fitness is
        // computed live from the journal window on every status read.
        .route("/meta/current", get(meta_current))
        .route("/meta/evaluate", post(meta_current_post))
        .route("/meta/history", get(meta_history))
        .route("/meta/evolve", post(meta_evolve))
        .route("/meta/rollback", post(meta_rollback))
        // Slice A5 (L5 Governance API — spec §12). Same posture as /meta/*:
        // 127.0.0.1 + bearer token, sidecar roundtrip per op, single
        // governance_result reply paired by `id`. Routes are tagged with
        // their operation class (read/evolve/govern) as code comments; v1
        // honors all three under the same token. The helper below mirrors
        // `meta_roundtrip` line-by-line but filters on governance_result.
        .route("/governance/policy",   get(governance_policy))             // read
        .route("/governance/proposals", get(governance_proposals))          // read
        .route("/governance/history",  get(governance_history_route))       // read
        .route("/governance/verify",   get(governance_verify_route))        // read
        .route("/governance/propose",   post(governance_propose_route))      // evolve
        .route("/governance/approve",   post(governance_approve_route))      // govern
        .route("/governance/reject",    post(governance_reject_route))       // govern
        .route("/governance/rollback",  post(governance_rollback_route))     // govern
        .route("/governance/freeze",    post(governance_freeze_route))       // govern
        .route("/governance/unfreeze",  post(governance_unfreeze_route))     // govern
        .route("/events", get(runtime_events))
        // Phase 1 (2026-07-07) — canonical provider + connector catalogs.
        // Both surfaces (Go TUI wizard, desktop React OnboardingWizard)
        // hit these at boot instead of carrying their own copy. The
        // response carries an `X-Feral-Catalog-Version` header —
        // clients treat a mismatch as "fall back to the bundled slice
        // with a clearly surfaced warning", never as a silent drop.
        .route("/runtime/providers/catalog", get(runtime_providers_catalog))
        .route("/runtime/connectors/catalog", get(runtime_connectors_catalog))
        // Auth runs before any handler. `from_fn_with_state` hands the token
        // to the middleware so it can compare in constant time.
        .layer(middleware::from_fn_with_state(state.clone(), require_token))
        .with_state(state)
        .layer(cors)
}

/// Reject any request without a valid bearer token. CORS preflight
/// (`OPTIONS`) is allowed through so browsers can negotiate before the real
/// request carries the `Authorization` header.
async fn require_token(
    State(state): State<ApiState>,
    req: Request<axum::body::Body>,
    next: Next,
) -> Response {
    if req.method() == axum::http::Method::OPTIONS {
        return next.run(req).await;
    }
    let presented = req
        .headers()
        .get(header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.strip_prefix("Bearer "))
        .map(str::trim)
        .unwrap_or("");
    if constant_time_eq(presented.as_bytes(), state.token.as_bytes()) {
        next.run(req).await
    } else {
        (StatusCode::UNAUTHORIZED, "missing or invalid bearer token").into_response()
    }
}

/// Length-independent byte comparison. Localhost timing attacks are a stretch,
/// but a token check is exactly the place to not get cute — the cost is one
/// XOR per byte.
fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

pub async fn serve(state: ApiState, port: u16) -> anyhow::Result<()> {
    let app = router(state);
    // Loopback only — see module docstring. Binding to 0.0.0.0 here exposed
    // model deletion and inference to every host on the network.
    let addr = format!("127.0.0.1:{}", port);
    tracing::info!(%addr, "feral api listening (loopback, token-gated)");
    let listener = tokio::net::TcpListener::bind(&addr).await?;
    axum::serve(listener, app).await?;
    Ok(())
}

async fn api_tags() -> impl IntoResponse {
    let models = models::scan_models_dir().unwrap_or_default();
    let items: Vec<Value> = models.into_iter().map(|m| {
        json!({
            "name": m.name,
            "model": m.id,
            "size": m.size_bytes,
            "details": {
                "quantization_level": m.quant,
                "format": "gguf",
            }
        })
    }).collect();
    Json(json!({ "models": items }))
}

#[derive(Deserialize)]
struct ShowReq { name: String }

async fn api_show(Json(req): Json<ShowReq>) -> impl IntoResponse {
    let models = models::scan_models_dir().unwrap_or_default();
    match models.into_iter().find(|m| m.name == req.name || m.id == req.name) {
        Some(m) => Json(json!({
            "model": m.name,
            "size": m.size_bytes,
            "quant": m.quant,
            "modelfile": m.modelfile,
        })).into_response(),
        None => (StatusCode::NOT_FOUND, "not found").into_response(),
    }
}

#[derive(Deserialize)]
struct DeleteReq { name: String }

async fn api_delete(Json(req): Json<DeleteReq>) -> impl IntoResponse {
    let models_dir = crate::paths::models_dir();
    let path = match resolve_model_path_secure(&models_dir, &req.name) {
        Some(p) => p,
        None => return (StatusCode::BAD_REQUEST, "invalid or unsafe model name").into_response(),
    };
    match models::delete_model(&path) {
        Ok(_) => StatusCode::NO_CONTENT.into_response(),
        Err(e) => {
            tracing::warn!(path=%path.display(), error=%e, "api_delete failed");
            (StatusCode::NOT_FOUND, "model not found or could not be deleted").into_response()
        }
    }
}

/// Resolve a caller-supplied model name to a path inside `models_dir`, or
/// `None` if the name is not a safe, contained filename.
///
/// Three layers of defense:
///   1. Reject anything that isn't a bare filename — empty, containing a path
///      separator, a `..` component, or an absolute/rooted path. This blocks
///      the obvious `../../etc/passwd` and `C:\Windows\...` shapes before any
///      filesystem call.
///   2. Confirm the joined path's parent canonicalizes to the models
///      directory. This catches anything the first check missed (symlinks,
///      platform-specific quirks) by comparing real on-disk locations.
///   3. After canonicalizing the *final* path, verify it still starts with
///      the canonical models directory. This defends against TOCTOU races
///      and symlink tricks that swap targets between the parent check and
///      the actual operation.
fn resolve_model_path_secure(models_dir: &std::path::Path, name: &str) -> Option<std::path::PathBuf> {
    let name = name.trim();
    if name.is_empty() {
        return None;
    }
    let candidate = std::path::Path::new(name);
    // Must be exactly one normal path component (the filename itself).
    let mut comps = candidate.components();
    let only = match (comps.next(), comps.next()) {
        (Some(std::path::Component::Normal(c)), None) => c,
        _ => return None,
    };
    if only != std::ffi::OsStr::new(name) {
        return None;
    }
    // Canonicalize the models directory; if it doesn't exist there's nothing to delete.
    let real_dir = models_dir.canonicalize().ok()?;
    let path = models_dir.join(only);
    // Containment check #1: the parent of the candidate must *be* the real models dir.
    let real_parent = path.parent()?.canonicalize().ok()?;
    if real_parent != real_dir {
        return None;
    }
    // Containment check #2 (defense in depth): if the file itself exists,
    // its canonical path must still start with the real models directory.
    if let Ok(real_path) = path.canonicalize() {
        if !real_path.starts_with(&real_dir) {
            return None;
        }
    }
    Some(path)
}

#[derive(Deserialize)]
struct GenerateReq {
    model: String,
    prompt: String,
    #[serde(default)]
    stream: Option<bool>,
    #[serde(default)]
    options: Option<Value>,
    #[serde(default)]
    max_tokens: Option<u32>,
}

async fn api_generate(
    State(state): State<ApiState>,
    Json(req): Json<GenerateReq>,
) -> impl IntoResponse {
    let messages = vec![Message { role: "user".into(), content: req.prompt, images: None }];
    let mut params = params_from_options(req.options.as_ref());
    apply_max_tokens(&mut params, req.max_tokens);

    if req.stream.unwrap_or(true) {
        sse_from_chat(state, req.model, messages, params, false).into_response()
    } else {
        let text = collect_chat(&state, messages, params).await;
        Json(json!({
            "model": req.model,
            "response": text,
            "done": true,
        })).into_response()
    }
}

/// OpenAI-compatible message content: either a plain string or an array of
/// content parts (`[{ "type": "text", "text": "..." }, ...]`). OpenAI-spec
/// clients send the array form; llama.cpp only needs the text.
#[derive(Deserialize)]
#[serde(untagged)]
enum FlexContent {
    Text(String),
    Parts(Vec<ContentPart>),
}

#[derive(Deserialize)]
struct ContentPart {
    #[serde(default)]
    text: Option<String>,
}

impl FlexContent {
    /// Flatten to a single string. Array parts are concatenated; non-text
    /// parts (images, etc.) contribute nothing since llama.cpp is text-only.
    fn into_string(self) -> String {
        match self {
            FlexContent::Text(s) => s,
            FlexContent::Parts(parts) => parts
                .into_iter()
                .filter_map(|p| p.text)
                .collect::<Vec<_>>()
                .join(""),
        }
    }
}

#[derive(Deserialize)]
struct ApiMessage {
    role: String,
    #[serde(default)]
    content: Option<FlexContent>,
}

impl From<ApiMessage> for Message {
    fn from(m: ApiMessage) -> Self {
        Message {
            role: m.role,
            content: m.content.map(FlexContent::into_string).unwrap_or_default(),
            images: None,
        }
    }
}

#[derive(Deserialize)]
struct ChatReq {
    model: String,
    messages: Vec<ApiMessage>,
    #[serde(default)]
    stream: Option<bool>,
    #[serde(default)]
    options: Option<Value>,
    /// OpenAI-standard generation cap. OpenAI-spec clients send this at the
    /// top level (not nested under `options`). Without honoring it, every
    /// agent request fell back to the 1024-token default and ran for
    /// minutes of CPU inference, appearing to hang.
    #[serde(default)]
    max_tokens: Option<u32>,
    /// Feral extension: a GBNF grammar that constrains decoding. The agent
    /// sidecar sends this to force valid tool-call JSON (grammar-constrained
    /// decoding). Standard OpenAI clients omit it and get unconstrained output.
    #[serde(default)]
    grammar: Option<String>,
    /// Feral extension: trigger strings for lazy grammar enforcement (see
    /// `InferParams::grammar_triggers`). The grammar engages only after one of
    /// these appears, so prose stays unconstrained and only the tool call is.
    #[serde(default)]
    grammar_triggers: Option<Vec<String>>,
    /// Feral extension (P1 — prompt caching): caller-supplied session id
    /// threaded into the audit log so a row can be cross-referenced with
    /// what the user saw. The bundled llama.cpp engine draws contexts from
    /// a small pool (P6); each context keeps its own KV prefix-diff record,
    /// and reuse is opportunistic — a caller that lands on a context whose
    /// cache shares its prefix benefits, regardless of session id. The
    /// field is plumbed through now so a future session→context affinity
    /// strategy can be added without another breaking schema change.
    #[serde(default)]
    session_id: Option<String>,
}

impl ChatReq {
    /// Convert incoming OpenAI-style messages into Feral's internal `Message`.
    fn into_messages(self) -> Vec<Message> {
        self.messages.into_iter().map(Message::from).collect()
    }
}

/// One lazy-load at a time — a burst of eval requests must not stack up N
/// concurrent `manager.load` calls for the same model.
static API_AUTOLOAD_IN_FLIGHT: std::sync::atomic::AtomicBool =
    std::sync::atomic::AtomicBool::new(false);

/// Ensure a model is loaded before serving a completion.
///
/// Boot auto-load was deliberately removed (2026-06-30: mmap lag froze
/// non-technical users' machines), so nothing guarantees a loaded model when
/// an API caller arrives — the RSI Dream Cycle's first episode burned every
/// eval on "no model loaded", and connectors hit the same hole whenever the
/// user hadn't touched the Local Models tab. The fix that respects the
/// no-boot-load decision: load lazily HERE, on first demand, using the model
/// id the caller asked for (falling back to the first model on disk). Waits
/// out a concurrent load (UI or another request) up to `FERAL_MODEL_WAIT_MS`
/// (default 120s).
async fn wait_for_model(state: &ApiState, requested: &str) -> bool {
    use std::sync::atomic::Ordering;
    if state.manager.current().is_some() {
        return true;
    }

    if !API_AUTOLOAD_IN_FLIGHT.swap(true, Ordering::SeqCst) {
        // We own the load. Resolve the requested id against the models dir.
        let requested = requested.to_string();
        let manager = state.manager.clone();
        let loaded = tokio::task::spawn_blocking(move || {
            let models = models::scan_models_dir().unwrap_or_default();
            let pick = models
                .iter()
                .find(|m| m.id == requested || m.name == requested)
                .or_else(|| models.first());
            match pick {
                Some(m) => {
                    tracing::info!(model = %m.id, "api: lazy-loading model on first completion request");
                    // n_gpu_layers -1 = offload all (GPU builds fall back to
                    // CPU internally); context uses the conservative default
                    // cap — the UI's Hardware choice re-applies on its next
                    // explicit load.
                    manager.load(m.path.clone(), -1, None).map(|_| true).unwrap_or(false)
                }
                None => false,
            }
        })
        .await
        .unwrap_or(false);
        API_AUTOLOAD_IN_FLIGHT.store(false, Ordering::SeqCst);
        if loaded {
            return true;
        }
        // Fall through to the wait loop — a concurrent UI load may still land.
    }

    let deadline_ms = std::env::var("FERAL_MODEL_WAIT_MS")
        .ok()
        .and_then(|v| v.trim().parse::<u64>().ok())
        .unwrap_or(120_000);
    let start = std::time::Instant::now();
    while start.elapsed().as_millis() < u128::from(deadline_ms) {
        if state.manager.current().is_some() {
            return true;
        }
        if !API_AUTOLOAD_IN_FLIGHT.load(Ordering::SeqCst) {
            // No load in flight anymore and still no model → nothing on disk
            // or the load failed; give the caller a real error now.
            if state.manager.current().is_none() {
                return false;
            }
        }
        tokio::time::sleep(std::time::Duration::from_millis(500)).await;
    }
    false
}

/// The 503 body both chat endpoints return when `wait_for_model` gives up.
/// A real status code (not an empty 200) lets the sidecar's router treat it
/// as a failed call it can surface, instead of a silent empty response.
fn no_model_response() -> axum::response::Response {
    (
        StatusCode::SERVICE_UNAVAILABLE,
        Json(json!({ "error": { "message": "no model loaded", "type": "model_not_ready" } })),
    )
        .into_response()
}

async fn api_chat(
    State(state): State<ApiState>,
    Json(req): Json<ChatReq>,
) -> impl IntoResponse {
    if !wait_for_model(&state, &req.model).await {
        return no_model_response();
    }
    let mut params = params_from_options(req.options.as_ref());
    apply_max_tokens(&mut params, req.max_tokens);
    apply_grammar(&mut params, &req);
    apply_session(&mut params, &req);
    let model = req.model.clone();
    let stream = req.stream.unwrap_or(true);
    let messages = req.into_messages();
    if stream {
        sse_from_chat(state, model, messages, params, false).into_response()
    } else {
        let text = collect_chat(&state, messages, params).await;
        Json(json!({
            "model": model,
            "message": { "role": "assistant", "content": text },
            "done": true,
        })).into_response()
    }
}

#[derive(Deserialize)]
struct TokenizeReq {
    content: String,
    /// Accepted for llama.cpp-server compatibility; tokenization always uses
    /// the currently loaded model.
    #[serde(default)]
    #[allow(dead_code)]
    model: Option<String>,
}

/// Count tokens with the loaded model's tokenizer. Returns `{"count": n}` —
/// the sidecar's `tokenizeLocal()` accepts either a `tokens` array or a
/// `count`; sending only the count avoids serializing thousands of ids for
/// long prompts.
async fn api_tokenize(
    State(state): State<ApiState>,
    Json(req): Json<TokenizeReq>,
) -> impl IntoResponse {
    match state.manager.count_tokens(&req.content) {
        Ok(n) => Json(json!({ "count": n })).into_response(),
        Err(e) => (StatusCode::SERVICE_UNAVAILABLE, e.to_string()).into_response(),
    }
}

async fn v1_models() -> impl IntoResponse {
    let models = models::scan_models_dir().unwrap_or_default();
    let data: Vec<Value> = models.into_iter().map(|m| {
        json!({ "id": m.id, "object": "model", "owned_by": "feral" })
    }).collect();
    Json(json!({ "object": "list", "data": data }))
}

// ── Public Runtime API v1 (Faza 4.5 Slice 3) ──────────────────────────────
//
// All handlers here read from `state.runtime` (the host-agnostic RuntimeState)
// so every host — desktop or headless gateway — serves identical answers
// (invariant 11). Nothing here fabricates: fields the runtime cannot source
// locally (connectors/memories/dreams live in the sidecar) are reported as
// `null` until the sidecar-round-trip vertical wires them.

#[derive(Deserialize)]
struct RuntimeChatReq {
    /// The user's new message. The sidecar owns per-session history (unified
    /// memory, invariant 11), so we forward only the new turn, not a transcript.
    content: String,
    /// Session key. Every client that shares a `session_id` shares one
    /// conversation + memory. Defaults to `api` per spec D3.
    #[serde(default = "default_session")]
    session_id: String,
    /// SSE token stream (default) vs a single JSON reply.
    #[serde(default = "default_true")]
    stream: bool,
}
fn default_session() -> String { "api".to_string() }
fn default_true() -> bool { true }

/// How long to wait for the next reply fragment before giving up. Local
/// inference plus a tool call can be slow; 120s idle is generous without
/// hanging a dead sidecar's socket open forever.
const CHAT_IDLE_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(120);

/// D3: forward a chat turn to the supervised sidecar and stream the reply.
///
/// The sidecar broadcasts *all* output on one bus as `feral://agent-output`
/// events (no per-request socket), so we correlate our reply by the message
/// `id` we generate: subscribe to the bus BEFORE sending (no lost-first-token
/// race), send `{"type":"message", id, content, sessionId}`, then keep only
/// `chunk`/`done` events whose `id` matches ours. Same session, same memory,
/// same LoRA, same tools as the desktop and the connectors — this is just
/// another face on the one brain.
async fn runtime_chat(
    State(state): State<ApiState>,
    Json(req): Json<RuntimeChatReq>,
) -> Response {
    let rt = &state.runtime;

    // Grab the sidecar sender without holding the lock across the await.
    let tx = {
        let guard = rt.feral_agent_tx.lock();
        match guard.as_ref() {
            Some(tx) => tx.clone(),
            None => {
                return (StatusCode::SERVICE_UNAVAILABLE, "feral-agent sidecar is not running")
                    .into_response()
            }
        }
    };

    let msg_id = uuid::Uuid::new_v4().to_string();
    // Subscribe BEFORE sending so we can't miss the first chunk.
    let rx = rt.events_tx.subscribe();

    let outbound = json!({
        "type": "message",
        "id": msg_id,
        "content": req.content,
        "sessionId": req.session_id,
    })
    .to_string();
    if tx.send(outbound).await.is_err() {
        return (StatusCode::SERVICE_UNAVAILABLE, "feral-agent sidecar stopped accepting messages")
            .into_response();
    }

    if req.stream {
        sse_from_agent_reply(rx, msg_id).into_response()
    } else {
        // Non-stream: the `done` event already carries the full text, so we
        // just wait for our matching `done` instead of accumulating chunks.
        match await_agent_reply(rx, &msg_id).await {
            Ok(text) => Json(json!({
                "id": msg_id,
                "session_id": req.session_id,
                "content": text,
            }))
            .into_response(),
            Err(e) => (StatusCode::GATEWAY_TIMEOUT, e).into_response(),
        }
    }
}

/// Pull one line's `type`+`id`+`content` out of a `feral://agent-output`
/// broadcast event, if it is one. The payload is `{"data": "<json line>"}`
/// where the line is itself the sidecar's JSON event.
///
/// For tool events we also surface the structured fields (tool name, args,
/// progress message, result) so the SSE layer can re-emit them as typed
/// `event:` lines — see `sse_from_agent_reply`.
fn parse_agent_output(ev: &crate::host::HostEvent) -> Option<AgentOutputLine> {
    if ev.event != "feral://agent-output" {
        return None;
    }
    let line = ev.payload.get("data")?.as_str()?;
    let v: Value = serde_json::from_str(line).ok()?;
    let ty = v.get("type")?.as_str()?.to_string();
    let id = v.get("id").and_then(|x| x.as_str()).unwrap_or("").to_string();
    // `chunk`/`done` carry the text in `content`; `error` carries it in
    // `message`. Fall back so the correlator can surface failures too.
    let content = v
        .get("content")
        .and_then(|x| x.as_str())
        .or_else(|| v.get("message").and_then(|x| x.as_str()))
        .unwrap_or("")
        .to_string();
    Some(AgentOutputLine {
        ty,
        id,
        content,
        raw: v,
    })
}

/// Flattened one-line view of a `feral://agent-output` payload, with the
/// original `Value` retained so tool events can be re-serialised with their
/// structured fields intact (`tool_start.tool`, `tool_done.result`, …).
///
/// `Debug` and `PartialEq` are derived so the test module below can use
/// `assert_eq!`; the `Value` in `raw` participates in equality via serde_json's
/// `Value` impls, which is fine because the fields are deterministic for
/// each input.
#[derive(Debug, PartialEq)]
struct AgentOutputLine {
    ty: String,
    id: String,
    content: String,
    raw: Value,
}

/// Wait for the `done` event matching `msg_id`, returning its full text.
/// Used by the non-stream path.
async fn await_agent_reply(
    mut rx: broadcast::Receiver<crate::host::HostEvent>,
    msg_id: &str,
) -> Result<String, String> {
    loop {
        match tokio::time::timeout(CHAT_IDLE_TIMEOUT, rx.recv()).await {
            Ok(Ok(ev)) => {
                if let Some(line) = parse_agent_output(&ev) {
                    if line.id == msg_id {
                        match line.ty.as_str() {
                            "done" => return Ok(line.content),
                            "error" => return Err(format!("sidecar inference error: {}", line.content)),
                            _ => {}
                        }
                    }
                }
            }
            Ok(Err(broadcast::error::RecvError::Lagged(_))) => continue,
            Ok(Err(broadcast::error::RecvError::Closed)) => {
                return Err("runtime event bus closed before reply completed".into())
            }
            Err(_) => return Err("timed out waiting for sidecar reply".into()),
        }
    }
}

/// SSE the reply for `msg_id` as OpenAI-style chat chunks (so any OpenAI SSE
/// client — and `feral chat` — can consume it), terminating with `[DONE]`.
///
/// `tool_start` / `tool_progress` / `tool_done` events matching `msg_id` are
/// re-emitted as **typed SSE events** (separate `event:` lines, not on
/// `data:`) so plain OpenAI clients ignore them while tool-aware clients
/// (`feral chat`, future agents) can render a tool-call stream without
/// polluting the answer text.
fn sse_from_agent_reply(
    rx: broadcast::Receiver<crate::host::HostEvent>,
    msg_id: String,
) -> Sse<impl Stream<Item = Result<Event, Infallible>>> {
    use async_stream::stream;
    let s = stream! {
        let mut rx = rx;
        loop {
            let recv = tokio::time::timeout(CHAT_IDLE_TIMEOUT, rx.recv()).await;
            match recv {
                Ok(Ok(ev)) => {
                    let Some(line) = parse_agent_output(&ev) else { continue };
                    if line.id != msg_id { continue; }
                    match line.ty.as_str() {
                        "chunk" => {
                            let payload = json!({
                                "id": format!("chatcmpl-{msg_id}"),
                                "object": "chat.completion.chunk",
                                "choices": [{ "index": 0, "delta": { "content": line.content } }],
                            });
                            yield Ok::<_, Infallible>(Event::default().data(payload.to_string()));
                        }
                        "done" => {
                            let payload = json!({
                                "id": format!("chatcmpl-{msg_id}"),
                                "object": "chat.completion.chunk",
                                "choices": [{ "index": 0, "delta": {}, "finish_reason": "stop" }],
                            });
                            yield Ok(Event::default().data(payload.to_string()));
                            yield Ok(Event::default().data("[DONE]"));
                            break;
                        }
                        "tool_start" => {
                            // Re-serialise the raw event with the original id
                            // embedded — the sidecar emits `id` per call, and
                            // clients correlate tool_start → tool_done by it.
                            yield Ok(Event::default()
                                .event("tool_start")
                                .data(line.raw.to_string()));
                        }
                        "tool_progress" => {
                            yield Ok(Event::default()
                                .event("tool_progress")
                                .data(line.raw.to_string()));
                        }
                        "tool_done" => {
                            yield Ok(Event::default()
                                .event("tool_done")
                                .data(line.raw.to_string()));
                        }
                        "error" => {
                            // Surface the sidecar's inference error to the client
                            // instead of hanging until the idle timeout.
                            tracing::warn!(msg_id = %msg_id, error = %line.content, "/runtime/chat sidecar error");
                            let payload = json!({
                                "id": format!("chatcmpl-{msg_id}"),
                                "object": "chat.completion.chunk",
                                "choices": [{ "index": 0, "delta": {}, "finish_reason": "error" }],
                                "error": line.content,
                            });
                            yield Ok(Event::default().data(payload.to_string()));
                            yield Ok(Event::default().data("[DONE]"));
                            break;
                        }
                        _ => {} // usage / budget_warning / etc. — metadata, not text or tool
                    }
                }
                Ok(Err(broadcast::error::RecvError::Lagged(n))) => {
                    tracing::warn!(skipped = n, "/runtime/chat subscriber lagged");
                    continue;
                }
                Ok(Err(broadcast::error::RecvError::Closed)) => break,
                Err(_) => {
                    // Idle timeout — close the stream rather than hang.
                    tracing::warn!(msg_id = %msg_id, "/runtime/chat idle timeout");
                    yield Ok(Event::default().data("[DONE]"));
                    break;
                }
            }
        }
    };
    Sse::new(s)
}

/// Slice 4b: poke the sidecar to reconcile connectors against the on-disk
/// `~/.feral/connectors.json` — the same `connectors_reload` message the desktop
/// app sends. 503 if the sidecar isn't running.
async fn runtime_connectors_reload(State(state): State<ApiState>) -> impl IntoResponse {
    let tx = { state.runtime.feral_agent_tx.lock().as_ref().cloned() };
    match tx {
        Some(tx) => {
            if tx.send(json!({ "type": "connectors_reload" }).to_string()).await.is_err() {
                return (StatusCode::SERVICE_UNAVAILABLE, "sidecar stopped accepting messages")
                    .into_response();
            }
            Json(json!({ "ok": true, "reloaded": true })).into_response()
        }
        None => {
            (StatusCode::SERVICE_UNAVAILABLE, "feral-agent sidecar is not running").into_response()
        }
    }
}

// ── Faza 6 (L6) Meta Evolution ──────────────────────────────────────────────

async fn meta_current(state: State<ApiState>) -> Response {
    meta_roundtrip(state, "meta_status").await
}
/// POST alias for `/meta/evaluate` — same live status+fitness payload.
async fn meta_current_post(state: State<ApiState>) -> Response {
    meta_roundtrip(state, "meta_status").await
}
async fn meta_history(state: State<ApiState>) -> Response {
    meta_roundtrip(state, "meta_history").await
}
async fn meta_evolve(state: State<ApiState>) -> Response {
    meta_roundtrip(state, "meta_evolve").await
}
async fn meta_rollback(state: State<ApiState>) -> Response {
    meta_roundtrip(state, "meta_rollback").await
}

/// Send one meta_* command to the sidecar and return its `meta_result`
/// reply, correlated by the generated `id` on the shared agent-output bus
/// (same subscribe-before-send discipline as `/runtime/chat`).
/// Sprint 1.6 — Memory Resume. Same subscribe-before-send discipline as
/// `meta_roundtrip`; differs only in the inbound `type` ("resume_get") and
/// the matched outbound reply type ("resume_get_result"). The Tauri desktop
/// command `get_last_task` inlines the same pattern (see
/// `src-tauri/src/memory_resume.rs`) so the two call paths can't drift.
async fn runtime_resume(State(state): State<ApiState>) -> Response {
    let tx = { state.runtime.feral_agent_tx.lock().as_ref().cloned() };
    let Some(tx) = tx else {
        // Sidecar isn't running — first launch with no memory, or gateway
        // running headless without the agent. Empty payload is the right
        // safe default so the TUI / curl callers can render "fresh start".
        return Json(json!({
            "task": null,
            "workspace_id": null,
            "workspace_name": null,
            "last_active_at": null,
        }))
        .into_response();
    };
    let msg_id = uuid::Uuid::new_v4().to_string();
    let mut rx = state.runtime.events_tx.subscribe();
    if tx
        .send(json!({ "type": "resume_get", "id": msg_id }).to_string())
        .await
        .is_err()
    {
        return Json(json!({
            "task": null,
            "workspace_id": null,
            "workspace_name": null,
            "last_active_at": null,
        }))
        .into_response();
    }
    let deadline = std::time::Duration::from_millis(1500);
    loop {
        match tokio::time::timeout(deadline, rx.recv()).await {
            Ok(Ok(ev)) => {
                if ev.event != "feral://agent-output" {
                    continue;
                }
                let Some(line) = ev.payload.get("data").and_then(|s| s.as_str()) else {
                    continue;
                };
                let Ok(v) = serde_json::from_str::<Value>(line) else { continue };
                if v.get("type").and_then(|t| t.as_str()) == Some("resume_get_result")
                    && v.get("id").and_then(|i| i.as_str()) == Some(msg_id.as_str())
                {
                    return Json(v).into_response();
                }
            }
            Ok(Err(broadcast::error::RecvError::Lagged(_))) => continue,
            Ok(Err(broadcast::error::RecvError::Closed)) => {
                return Json(json!({
                    "task": null,
                    "workspace_id": null,
                    "workspace_name": null,
                    "last_active_at": null,
                }))
                .into_response();
            }
            Err(_) => {
                return Json(json!({
                    "task": null,
                    "workspace_id": null,
                    "workspace_name": null,
                    "last_active_at": null,
                }))
                .into_response();
            }
        }
    }
}

async fn meta_roundtrip(State(state): State<ApiState>, op: &'static str) -> Response {
    let tx = { state.runtime.feral_agent_tx.lock().as_ref().cloned() };
    let Some(tx) = tx else {
        return (StatusCode::SERVICE_UNAVAILABLE, "feral-agent sidecar is not running")
            .into_response();
    };
    let msg_id = uuid::Uuid::new_v4().to_string();
    let mut rx = state.runtime.events_tx.subscribe();
    if tx.send(json!({ "type": op, "id": msg_id }).to_string()).await.is_err() {
        return (StatusCode::SERVICE_UNAVAILABLE, "sidecar stopped accepting messages")
            .into_response();
    }
    let deadline = std::time::Duration::from_secs(10);
    loop {
        match tokio::time::timeout(deadline, rx.recv()).await {
            Ok(Ok(ev)) => {
                if ev.event != "feral://agent-output" {
                    continue;
                }
                let Some(line) = ev.payload.get("data").and_then(|s| s.as_str()) else { continue };
                let Ok(v) = serde_json::from_str::<Value>(line) else { continue };
                if v.get("type").and_then(|t| t.as_str()) == Some("meta_result")
                    && v.get("id").and_then(|i| i.as_str()) == Some(msg_id.as_str())
                {
                    return Json(v).into_response();
                }
            }
            Ok(Err(broadcast::error::RecvError::Lagged(_))) => continue,
            Ok(Err(broadcast::error::RecvError::Closed)) => {
                return (StatusCode::SERVICE_UNAVAILABLE, "runtime event bus closed").into_response()
            }
            Err(_) => {
                return (StatusCode::GATEWAY_TIMEOUT, "timed out waiting for meta_result")
                    .into_response()
            }
        }
    }
}

// ── Slice A5 (L5 Governance API — spec §12) ─────────────────────────────
//
// Mirrors `meta_roundtrip` line-by-line: subscribe-before-send, wait on the
// runtime event bus for one `governance_result` correlated by `id`. Differs
// in three ways:
//   1. Filters on `type == "governance_result"` (the new reply union in
//      `FeralAgent/src/types.ts`) instead of `"meta_result"`.
//   2. Accepts an optional JSON body whose top-level fields are flattened
//      onto the outbound message alongside `type` + `id`. The sidecar's
//      handler (`FeralAgent/src/index.ts`) reads these fields directly —
//      no per-op message shape was added.
//   3. Per spec §12 the routes are tagged read/evolve/govern in comments
//      (no enforcement in v1; a future RBAC layer will branch on the tag).

/// Forward a governance op to the sidecar and return its `governance_result`.
/// Optional `body` fields are flattened onto the outbound message envelope.
async fn governance_roundtrip(
    State(state): State<ApiState>,
    op: &'static str,
    body: Option<Json<Value>>,
) -> Response {
    let tx = { state.runtime.feral_agent_tx.lock().as_ref().cloned() };
    let Some(tx) = tx else {
        return (StatusCode::SERVICE_UNAVAILABLE, "feral-agent sidecar is not running")
            .into_response();
    };
    let msg_id = uuid::Uuid::new_v4().to_string();
    let mut rx = state.runtime.events_tx.subscribe();

    // Build the outbound envelope. Body fields overwrite defaults; missing
    // body → minimal `{ type, id }` envelope (the sidecar's handler defaults
    // missing fields to sensible empties — see brief §1 op-mapping table).
    let mut payload = json!({ "type": op, "id": msg_id });
    if let Some(Json(Value::Object(map))) = body {
        for (k, v) in map {
            payload[k] = v;
        }
    }
    if tx.send(payload.to_string()).await.is_err() {
        return (StatusCode::SERVICE_UNAVAILABLE, "sidecar stopped accepting messages")
            .into_response();
    }
    let deadline = std::time::Duration::from_secs(10);
    loop {
        match tokio::time::timeout(deadline, rx.recv()).await {
            Ok(Ok(ev)) => {
                if ev.event != "feral://agent-output" {
                    continue;
                }
                let Some(line) = ev.payload.get("data").and_then(|s| s.as_str()) else {
                    continue;
                };
                let Ok(v) = serde_json::from_str::<Value>(line) else {
                    continue;
                };
                if v.get("type").and_then(|t| t.as_str()) == Some("governance_result")
                    && v.get("id").and_then(|i| i.as_str()) == Some(msg_id.as_str())
                {
                    return Json(v).into_response();
                }
            }
            Ok(Err(broadcast::error::RecvError::Lagged(_))) => continue,
            Ok(Err(broadcast::error::RecvError::Closed)) => {
                return (StatusCode::SERVICE_UNAVAILABLE, "runtime event bus closed")
                    .into_response();
            }
            Err(_) => {
                return (StatusCode::GATEWAY_TIMEOUT, "timed out waiting for governance_result")
                    .into_response();
            }
        }
    }
}

/// Query params for `GET /governance/history?limit=N`. Mirrors the sidecar's
/// `historyRows(limit)` default of 50 (governance-lifecycle.ts:270).
#[derive(serde::Deserialize)]
struct GovernanceHistoryQuery {
    #[serde(default)]
    limit: Option<u64>,
}

/// `GET /governance/policy` — full active policy + head hash + pending list.
async fn governance_policy(State(state): State<ApiState>) -> Response {
    governance_roundtrip(State(state), "governance_status", None).await
}

/// `GET /governance/proposals` — pending proposals. The brief notes that
/// `governance_status` already carries `pending[]` in its payload, so this
/// route is a thin alias that returns the same shape — clients that want
/// ONLY pending proposals can ignore the rest.
async fn governance_proposals(State(state): State<ApiState>) -> Response {
    governance_roundtrip(State(state), "governance_status", None).await
}

/// `GET /governance/history?limit=N` — history rows, newest last (clamped
/// server-side by the lifecycle's default of 200).
async fn governance_history_route(
    State(state): State<ApiState>,
    Query(q): Query<GovernanceHistoryQuery>,
) -> Response {
    let body = q.limit.map(|l| Json(json!({ "limit": l })));
    governance_roundtrip(State(state), "governance_history", body).await
}

/// `GET /governance/verify` — chain + journal verification report.
async fn governance_verify_route(State(state): State<ApiState>) -> Response {
    governance_roundtrip(State(state), "governance_verify", None).await
}

/// `POST /governance/propose` — body: full policy JSON document.
async fn governance_propose_route(
    State(state): State<ApiState>,
    body: Option<Json<Value>>,
) -> Response {
    governance_roundtrip(State(state), "governance_propose", body).await
}

/// `POST /governance/approve` — body: {policyId, documentHash, note}.
async fn governance_approve_route(
    State(state): State<ApiState>,
    body: Option<Json<Value>>,
) -> Response {
    governance_roundtrip(State(state), "governance_approve", body).await
}

/// `POST /governance/reject` — body: {policyId, reason}.
async fn governance_reject_route(
    State(state): State<ApiState>,
    body: Option<Json<Value>>,
) -> Response {
    governance_roundtrip(State(state), "governance_reject", body).await
}

/// `POST /governance/rollback` — body optional (default reason: "operator rollback").
async fn governance_rollback_route(
    State(state): State<ApiState>,
    body: Option<Json<Value>>,
) -> Response {
    governance_roundtrip(State(state), "governance_rollback", body).await
}

/// `POST /governance/freeze` — body: {layers, reason}.
async fn governance_freeze_route(
    State(state): State<ApiState>,
    body: Option<Json<Value>>,
) -> Response {
    governance_roundtrip(State(state), "governance_freeze", body).await
}

/// `POST /governance/unfreeze` — body: {layers, reason}.
async fn governance_unfreeze_route(
    State(state): State<ApiState>,
    body: Option<Json<Value>>,
) -> Response {
    governance_roundtrip(State(state), "governance_unfreeze", body).await
}

/// Slice 4: request a graceful shutdown. Fires the runtime's shutdown signal;
/// the headless gateway's main loop wakes and runs the D7 drain. Token-gated +
/// loopback like everything else — a local holder of the token could already
/// drive inference and delete models, so letting it stop the daemon is no new
/// exposure. `feral gateway stop` calls this (no Windows signal games).
async fn runtime_shutdown(State(state): State<ApiState>) -> impl IntoResponse {
    tracing::info!("runtime: shutdown requested via /runtime/shutdown");
    state.runtime.shutdown.notify_waiters();
    // notify_one() as well, so a request that races ahead of the gateway's
    // `.notified()` still lands (stores a permit); notify_waiters alone would
    // be lost if no task is parked yet.
    state.runtime.shutdown.notify_one();
    Json(json!({ "ok": true, "shutting_down": true }))
}

/// Sprint 2 / audit C-1 — real hardware probe for the TUI Setup Wizard.
/// Returns the same `SystemInfo` shape the Tauri command exposes. The
/// wizard previously hard-coded "rtx 4070 · 12 GB" on every machine; this
/// reads the real GPU / VRAM / RAM via `sysinfo_mod::detect()` and the
/// optional `gpu_detect` shim. The probe is bounded by sysinfo_mod's
/// internal timeouts (a few seconds).
async fn system_info() -> Json<crate::sysinfo_mod::SystemInfo> {
    Json(crate::sysinfo_mod::collect())
}

/// Sprint 2 / audit C-2 — real provider key validation. Body:
/// `{ "provider_id": "...", "api_key": "...", "base_url"?: "..." }`.
/// Delegates to `byok::test_provider` so the desktop and headless paths
/// share one probe implementation. The wizard previously accepted any
/// pasted string; now a "401 Unauthorized" or "Invalid API key" surfaces
/// verbatim so the user can act on the actual provider response.
async fn providers_test(Json(req): Json<ProvidersTestReq>) -> Json<byok::TestProviderResponse> {
    Json(
        byok::test_provider(&req.provider_id, &req.api_key, req.base_url.as_deref()).await,
    )
}

#[derive(serde::Deserialize)]
struct ProvidersTestReq {
    provider_id: String,
    api_key: String,
    base_url: Option<String>,
}

#[derive(serde::Deserialize)]
struct SaveByokReq {
    provider_id: String,
    enabled: bool,
    api_key: String,
    base_url: Option<String>,
    default_model: Option<String>,
}

/// Persist a provider's API key to the OS keychain and its metadata to
/// `~/.feral/byok.json`. Mirrors the Tauri `save_byok_provider` command in
/// `src-tauri/src/lib.rs:2241` so the headless gateway exposes the same
/// single-provider write path.
///
/// Response is always JSON. The `api_key` is never echoed on either success
/// or failure — call sites already have the value from the input. Keyring
/// failures are classified into typed HTTP statuses so the wizard can render
/// an actionable message instead of a raw anyhow chain:
///
///   * `keyring::Error::NoStorageAccess` / `PlatformFailure` → 503
///     `{"error":"keyring_unavailable", hint: ...}`. The hint points at the
///     `api_key_source.kind: env` path for headless servers (per the
///     Phase-3 non-interactive slice).
///   * `keyring::Error::TooLong` / `Invalid` → 400 with a stable category.
///   * Anything else → 500 with a generic message.
///
/// Provider id validation: `[a-z0-9_-]{1,64}`. This mirrors the existing
/// default-provider ids (openai, anthropic, minnimax, etc.) and is the
/// conservative subset supported by every keychain backend the workspace
/// targets (Windows Credential Manager, macOS Keychain, Linux Secret
/// Service). The keyring crate accepts broader input but the schema
/// discipline here keeps lookup tables, filename components, and log lines
/// unambiguously parseable downstream.
async fn runtime_byok_save(Json(req): Json<SaveByokReq>) -> Response {
    let provider_id = req.provider_id.trim().to_string();
    if provider_id.is_empty() {
        return byok_save_error(
            StatusCode::BAD_REQUEST,
            "provider_id_required",
            "provider_id is required",
            None,
        );
    }
    if !is_safe_provider_id(&provider_id) {
        return byok_save_error(
            StatusCode::BAD_REQUEST,
            "invalid_provider_id",
            "provider_id may only contain [a-z0-9_-] and be 1-64 chars",
            None,
        );
    }

    let config = byok::ProviderConfig {
        enabled: req.enabled,
        api_key: req.api_key,
        base_url: req.base_url,
        default_model: req.default_model,
    };

    match byok::save_provider(&provider_id, config) {
        Ok(()) => Json(json!({
            "ok": true,
            "provider_id": provider_id,
        }))
        .into_response(),
        Err(e) => {
            // Walk the anyhow chain so we classify on the original
            // keyring::Error (not a transcribed Display string).
            for cause in e.chain() {
                if let Some(kre) = cause.downcast_ref::<keyring::Error>() {
                    let (status, code, hint) = classify_keyring_error(kre);
                    // Log full detail server-side only; the response body
                    // gets the sanitised category + hint.
                    tracing::warn!(
                        provider_id = %provider_id,
                        keyring_error = %kre,
                        category = %code,
                        "runtime_byok_save: keyring failure"
                    );
                    return byok_save_error(status, code, summary_for(code), hint);
                }
            }
            tracing::warn!(provider_id = %provider_id, error = %e, "runtime_byok_save: non-keyring failure");
            byok_save_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                "byok_save_failed",
                "Could not save the provider configuration.",
                Some(
                    "Try the setup again. If the problem keeps happening, run `feral doctor` to diagnose.",
                ),
            )
        }
    }
}

/// Build a `{ok: false, error, message, hint?}` JSON error response with the
/// given status. The `message` is a short user-facing summary; `hint` is an
/// optional next-step pointer. Both are deliberately generic — they never
/// echo the keyring error chain back to the caller (the server has already
/// logged it). Wrapping in `Json(value)` plus the explicit
/// `(axum::http::StatusCode, Json<Value>)` tuple keeps the inference
/// unambiguous across the workspace's multiple `StatusCode` exports.
fn byok_save_error(
    status: StatusCode,
    code: &'static str,
    message: &str,
    hint: Option<&'static str>,
) -> Response {
    let mut body = json!({
        "ok": false,
        "error": code,
        "message": message,
    });
    if let Some(h) = hint {
        body["hint"] = json!(h);
    }
    (status, Json(body)).into_response()
}

/// Map a `keyring::Error` to (http_status, error_code, optional_hint).
fn classify_keyring_error(e: &keyring::Error) -> (StatusCode, &'static str, Option<&'static str>) {
    match e {
        keyring::Error::NoStorageAccess(_) | keyring::Error::PlatformFailure(_) => (
            StatusCode::SERVICE_UNAVAILABLE,
            "keyring_unavailable",
            Some(
                "Could not access the OS credential store. On a headless server, \
                 run `feral setup --non-interactive --config=...` with \
                 `api_key_source.kind: env` to source the key from an environment variable.",
            ),
        ),
        keyring::Error::TooLong(_, _) => (
            StatusCode::BAD_REQUEST,
            "key_too_long",
            Some("The credential exceeds the platform length limit. Trim the key or use env-var sourcing."),
        ),
        keyring::Error::Invalid(_, _) => (
            StatusCode::BAD_REQUEST,
            "invalid_credential_attribute",
            Some("The keyring rejected the credential attribute. Check the provider id format."),
        ),
        _ => (StatusCode::INTERNAL_SERVER_ERROR, "byok_save_failed", None),
    }
}

fn summary_for(code: &str) -> &'static str {
    match code {
        "keyring_unavailable" => "Couldn't reach the OS credential store.",
        "key_too_long" => "The key is too long for this OS credential store.",
        "invalid_credential_attribute" => "The provider id or credential attribute is invalid for this OS credential store.",
        _ => "Could not save the provider configuration.",
    }
}

/// `[a-z0-9_-]{1,64}` — a conservative, parseable subset of the keychain
/// account-name character space that lines up with the existing default
/// provider ids (openai, anthropic, minnimax, ...) and avoids quotes,
/// backslashes, and Unicode line separators that some keychain backends
/// treat as field separators.
fn is_safe_provider_id(id: &str) -> bool {
    let len = id.len();
    if len == 0 || len > 64 {
        return false;
    }
    id.bytes()
        .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_' || b == b'-')
}

/// Sprint 2 / audit C-5 — start a model download. Returns immediately with
/// a download id (uuid v4); the actual work runs on a detached Tokio task
/// so the IPC reply never blocks. Progress is published via the
/// `runtime.model_downloads` map; the GET handler reads it.
async fn runtime_models_install(
    State(state): State<ApiState>,
    Json(req): Json<InstallModelReq>,
) -> Json<serde_json::Value> {
    use std::sync::atomic::AtomicBool;
    let id = uuid::Uuid::new_v4().to_string();
    let cancel = Arc::new(AtomicBool::new(false));

    // Insert an initial entry so the GET handler can find it immediately.
    state.runtime.model_downloads.lock().insert(
        id.clone(),
        crate::runtime::ModelDownload {
            id: id.clone(),
            repo_id: req.repo_id.clone(),
            filename: req.filename.clone(),
            progress: 0.0,
            status: "downloading".to_string(),
            error: None,
        },
    );

    let id_for_task = id.clone();
    let repo = req.repo_id.clone();
    let file = req.filename.clone();
    let downloads_map = state.runtime.model_downloads.clone();
    tokio::spawn(async move {
        let (tx, mut rx) = tokio::sync::mpsc::channel::<f32>(32);
        // Forward progress updates from the download task to the snapshot.
        let downloads_for_forwarder = downloads_map.clone();
        let id_for_forwarder = id_for_task.clone();
        tokio::spawn(async move {
            while let Some(p) = rx.recv().await {
                if let Some(entry) = downloads_for_forwarder.lock().get_mut(&id_for_forwarder) {
                    if entry.status == "downloading" {
                        entry.progress = p;
                    }
                }
            }
        });
        let result = models::download_hf_model(repo, file, tx, cancel).await;
        if let Some(entry) = downloads_map.lock().get_mut(&id_for_task) {
            match result {
                Ok(_) => {
                    entry.status = "complete".to_string();
                    entry.progress = 1.0;
                }
                Err(e) => {
                    entry.status = "failed".to_string();
                    entry.error = Some(format!("{e:#}"));
                }
            }
        }
    });

    Json(json!({ "id": id }))
}

#[derive(serde::Deserialize)]
struct InstallModelReq {
    repo_id: String,
    filename: String,
}

async fn runtime_models_download(
    State(state): State<ApiState>,
    axum::extract::Path(id): axum::extract::Path<String>,
) -> axum::response::Response {
    let entry = state.runtime.model_downloads.lock().get(&id).cloned();
    match entry {
        Some(d) => axum::Json(d).into_response(),
        None => (
            axum::http::StatusCode::NOT_FOUND,
            axum::Json(json!({ "error": "unknown download id" })),
        )
            .into_response(),
    }
}

/// D3: loaded model, active LoRA, sidecar liveness, backend, RSI engine mirror.
async fn runtime_status(State(state): State<ApiState>) -> impl IntoResponse {
    let rt = &state.runtime;
    let model = rt.manager.current().map(|m| {
        json!({ "name": m.name, "ctx_len": m.ctx_len, "n_ctx_train": m.n_ctx_train })
    });
    let sidecar_alive = rt.feral_agent_process.lock().is_some();
    let rsi_engine = rt.rsi_engine.lock().clone().map(|e| {
        json!({
            "running": e.running,
            "iteration": e.iteration,
            "best_score": e.best_score,
            "cost_so_far_usd": e.cost_so_far_usd,
            "concurrency": e.concurrency,
        })
    });
    // Active provider — read from env so the TUI can show "nvidia" / "minimax"
    // / "local" instead of relying on the backend label alone. The provider
    // is set at sidecar spawn time; a runtime switch updates the sidecar
    // but not this env var, so we also report the agent_model change below.
    let provider = std::env::var("FERAL_PROVIDER").unwrap_or_else(|_| "openai_compatible".to_string());
    let byok_provider = std::env::var("FERAL_BYOK_PROVIDER").ok();
    Json(json!({
        "model": model,
        // What the sidecar actually infers with (local GGUF name or a cloud
        // model id). For a cloud session `model` above is null but this is set.
        "agent_model": rt.active_agent_model.lock().clone(),
        "lora": crate::inference::active_lora_adapter(),
        "sidecar_alive": sidecar_alive,
        "backend": crate::inference::active_backend_label(),
        // Provider name as the sidecar sees it — "openai_compatible",
        // "anthropic", "nvidia" (BYOK alias), etc. The TUI picks one of these
        // for its status line.
        "provider": provider,
        // BYOK provider id (e.g. "nvidia", "minimax") when the gateway was
        // started with FERAL_BYOK_PROVIDER set. Null on a vanilla local boot.
        "byok_provider": byok_provider,
        "gpu": crate::inference::gpu_active(),
        "rsi_engine": rsi_engine,
    }))
}

/// D3: model inventory on disk + which one is loaded. `active` is the loaded
/// model's internal name; the inventory `id`s are the on-disk identifiers. We
/// return both rather than joining them — the two namespaces are not guaranteed
/// equal, and a wrong per-item `active` flag is worse than none.
///
/// Also lists BYOK cloud models whose provider has both an enabled flag and a
/// key in the OS keychain — the TUI uses the merged list to show what the
/// user can switch to without first opening the desktop Settings UI.
async fn runtime_models(State(state): State<ApiState>) -> impl IntoResponse {
    let active = state.runtime.manager.current().map(|m| m.name);
    let local = models::scan_models_dir().unwrap_or_default();
    let mut ids: Vec<String> = local.into_iter().map(|m| m.id).collect();
    // Merge BYOK cloud models. Each entry is tagged `provider:model` so the
    // /runtime/model handler can match without a separate lookup table.
    let settings = crate::settings::load();
    let byok = crate::byok::load(&settings);
    for p in byok.get_all_providers() {
        // Only list providers that have both an enabled flag AND a stored key.
        // Skip the local provider — it has no `default_model` for cloud use.
        if !p.enabled {
            continue;
        }
        if crate::byok::byok_get(&p.id).is_none() {
            continue;
        }
        if let Some(model) = p.default_model {
            ids.push(format!("{}:{}", p.id, model));
        }
    }
    Json(json!({ "models": ids, "active": active }))
}

#[derive(Deserialize)]
struct SetModelReq {
    id: String,
}

/// Headless counterpart of the desktop `feral_set_model` command. Supports
/// both paths now:
///   - Local: a GGUF id (or filename) already on disk → load via the manager,
///     tell the sidecar to talk to loopback.
///   - BYOK: a `provider:model` pair from the cloud inventory (e.g.
///     `nvidia:stepfun-ai/step-3.7-flash`, `minimax:MiniMax-M3`) → resolve
///     the provider's base URL + keychain API key, push a `set_model` to
///     the sidecar with the new provider/url/key/model so the next request
///     goes to the cloud endpoint.
///
/// Pure provider ids (`nvidia`, `minimax`) are also accepted and use the
/// provider's `default_model`.
async fn runtime_set_model(State(state): State<ApiState>, Json(req): Json<SetModelReq>) -> Response {
    let requested = req.id.trim().to_string();

    // ── Cloud / BYOK path ────────────────────────────────────────────────
    // Two accepted shapes: `provider:model` (precise) or `provider` alone
    // (use the configured default_model).
    let (provider_id, cloud_model) = match requested.split_once(':') {
        Some((pid, m)) => (pid.trim().to_string(), Some(m.trim().to_string())),
        None => (requested.clone(), None),
    };

    let settings = crate::settings::load();
    let byok = crate::byok::load(&settings);
    let provider_cfg = byok.get_provider(&provider_id).cloned();
    if let Some(cfg) = provider_cfg {
        if !cfg.enabled {
            return (
                StatusCode::BAD_REQUEST,
                format!("provider '{}' is disabled in ~/.feral/byok.json", provider_id),
            )
                .into_response();
        }
        // Resolve the cloud model: explicit `provider:model` wins, else the
        // provider's default_model. Strip any trailing `/v1` from the base
        // URL because the sidecar's openai_compatible path appends it.
        let model = cloud_model
            .or_else(|| byok.get_all_providers().iter().find(|p| p.id == provider_id).and_then(|p| p.default_model.clone()));
        let Some(model) = model else {
            return (
                StatusCode::NOT_FOUND,
                format!(
                    "provider '{}' has no default_model set in byok.json — \
                     pass an explicit model id like '{0}:<model-id>'",
                    provider_id
                ),
            )
                .into_response();
        };
        let api_key = crate::byok::byok_get(&provider_id).unwrap_or_default();
        if api_key.is_empty() {
            return (
                StatusCode::UNAUTHORIZED,
                format!(
                    "provider '{}' has no API key in the OS keychain — \
                     run `feral byok set {0} <key>` or paste one in Settings → Cloud Keys",
                    provider_id
                ),
            )
                .into_response();
        }
        // Resolve base URL (BYOK stores it WITH a trailing /v1; strip it).
        // Fall back to known well-known provider base URLs when byok.json
        // has null (MiniMax, Groq, etc.).
        let base_url = byok
            .get_all_providers()
            .into_iter()
            .find(|p| p.id == provider_id)
            .and_then(|p| p.base_url.clone())
            .map(|u| u.trim_end_matches('/').trim_end_matches("/v1").to_string())
            .or_else(|| match provider_id.as_str() {
                "minimax" => Some("https://api.minimax.chat/v1".into()),
                "groq"    => Some("https://api.groq.com/openai/v1".into()),
                _         => None,
            });
        let Some(base_url) = base_url else {
            return (
                StatusCode::NOT_FOUND,
                format!("provider '{}' has no base_url in byok.json", provider_id),
            )
                .into_response();
        };

        // Tell the sidecar to swap to the cloud provider. The sidecar's
        // `set_model` handler already supports a fresh provider/url/key
        // payload and reloads its router — see FeralAgent set-model.ts.
        let Some(tx) = state.runtime.feral_agent_tx.lock().as_ref().cloned() else {
            return (
                StatusCode::SERVICE_UNAVAILABLE,
                "feral-agent sidecar is not running — cannot switch cloud model",
            )
                .into_response();
        };
        let provider_kind = match provider_id.as_str() {
            "anthropic" => "anthropic",
            "google" => "google",
            _ => "openai_compatible",
        };
        // Cloud context windows are usually 200K-1M; default to 200K so the
        // sidecar's transcript budget matches the cloud model's real KV.
        let context_window = 200_000u32;
        let msg = json!({
            "type": "set_model",
            "provider": provider_kind,
            "model": model,
            "baseUrl": base_url,
            "apiKey": api_key,
            "contextWindow": context_window,
        })
        .to_string();
        if tx.try_send(msg).is_err() {
            return (
                StatusCode::SERVICE_UNAVAILABLE,
                "sidecar stopped accepting messages",
            )
                .into_response();
        }
        *state.runtime.active_agent_model.lock() = Some(model.clone());
        // Mirror the choice into env vars so runtime_status reports it and
        // a subsequent restart doesn't lose track of which cloud we picked.
        // SAFETY: we are single-threaded inside the router task at this point
        // and `provider_id` is not borrowed anywhere else after this block.
        unsafe {
            std::env::set_var("FERAL_PROVIDER", provider_kind);
            std::env::set_var("FERAL_BASE_URL", &base_url);
            std::env::set_var("FERAL_MODEL", &model);
            std::env::set_var("FERAL_BYOK_PROVIDER", &provider_id);
        }
        return Json(json!({
            "active": model,
            "provider": provider_id,
            "backend": provider_kind,
            "ctx_len": context_window,
        }))
        .into_response();
    }

    // ── Local path ───────────────────────────────────────────────────────
    let manager = state.manager.clone();
    let local_req = requested.clone();
    let picked = tokio::task::spawn_blocking(move || {
        let models = models::scan_models_dir().unwrap_or_default();
        models
            .into_iter()
            .find(|m| m.id == local_req || m.name == local_req)
    })
    .await
    .unwrap_or(None);

    let Some(model) = picked else {
        // Build a useful error so the TUI can show what IS available.
        let mut local_ids: Vec<String> = models::scan_models_dir()
            .unwrap_or_default()
            .into_iter()
            .map(|m| m.id)
            .collect();
        let mut cloud: Vec<String> = byok
            .get_all_providers()
            .into_iter()
            .filter(|p| p.enabled && crate::byok::byok_get(&p.id).is_some())
            .filter_map(|p| p.default_model.map(|m| format!("{}:{}", p.id, m)))
            .collect();
        local_ids.append(&mut cloud);
        return (
            StatusCode::NOT_FOUND,
            format!(
                "no model matches '{}' — available: {}",
                req.id,
                local_ids.join(", ")
            ),
        )
            .into_response();
    };

    let manager2 = manager.clone();
    let path = model.path.clone();
    let loaded = tokio::task::spawn_blocking(move || manager2.load(path, -1, None))
        .await
        .unwrap_or_else(|e| Err(anyhow::anyhow!(e)));

    let loaded = match loaded {
        Ok(l) => l,
        Err(e) => return (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()).into_response(),
    };

    // Tell the sidecar the context window changed (mirrors desktop path).
    if let Some(tx) = state.runtime.feral_agent_tx.lock().as_ref().cloned() {
        let msg = json!({
            "type": "set_model",
            "provider": "openai_compatible",
            "model": loaded.name,
            "baseUrl": format!("http://127.0.0.1:{}", state.runtime.settings.api_port),
            "apiKey": state.runtime.local_api_token.to_string(),
            "contextWindow": loaded.ctx_len,
        })
        .to_string();
        let _ = tx.try_send(msg);
    }
    *state.runtime.active_agent_model.lock() = Some(loaded.name.clone());
    // Local switch → restore the loopback provider label so runtime_status
    // doesn't keep reporting the previous cloud provider after a /model call
    // goes back to a local GGUF.
    unsafe {
        std::env::set_var("FERAL_PROVIDER", "openai_compatible");
        std::env::set_var("FERAL_BASE_URL", format!("http://127.0.0.1:{}", state.runtime.settings.api_port));
        std::env::set_var("FERAL_MODEL", &loaded.name);
        std::env::remove_var("FERAL_BYOK_PROVIDER");
    }

    Json(json!({ "active": loaded.name, "backend": "llama.cpp", "ctx_len": loaded.ctx_len })).into_response()
}

/// D3: the active LoRA adapter. Full adapter inventory is deferred — no disk
/// scanner is surfaced from feral-core yet, and reporting a fabricated list
/// would be worse than reporting only what is provably active.
async fn runtime_lora() -> impl IntoResponse {
    Json(json!({ "active": crate::inference::active_lora_adapter() }))
}

/// Most-recent conversations from `~/.feral/conversations/index.json`, sorted
/// newest-first and capped at `?limit=N` (default 5, max 50). The index is
/// maintained by the desktop app's `conversations` save/load command; on a
/// fresh install (no index) we return `[]` rather than 404 so the welcome
/// screen degrades gracefully.
///
/// Read-only — does not touch the per-conversation `.json` files (which can
/// be large), and never falls back to scanning those files to invent entries
/// the index doesn't know about (better to show fewer rows than hallucinated
/// ones).
async fn runtime_sessions(
    axum::extract::Query(params): axum::extract::Query<std::collections::HashMap<String, String>>,
) -> impl IntoResponse {
    let limit: usize = params
        .get("limit")
        .and_then(|s| s.parse().ok())
        .unwrap_or(5)
        .clamp(1, 50);
    let index_path = crate::paths::conversations_dir().join("index.json");
    let raw = match tokio::fs::read(&index_path).await {
        Ok(b) => b,
        // Missing index = no saved conversations yet. Empty list, not 404.
        Err(_) => return Json(json!({ "sessions": [] })).into_response(),
    };
    let v: Value = match serde_json::from_slice(&raw) {
        Ok(v) => v,
        Err(e) => {
            tracing::warn!(path = %index_path.display(), error = %e, "runtime_sessions: bad index.json");
            return Json(json!({ "sessions": [] })).into_response();
        }
    };
    let mut items: Vec<Value> = v
        .get("conversations")
        .and_then(|c| c.as_array())
        .cloned()
        .unwrap_or_default();
    // Newest first; index.json already keeps them sorted, but sort defensively
    // so a hand-edited or older index still gives the right order.
    items.sort_by(|a, b| {
        let av = a.get("updated_at").and_then(|x| x.as_str()).unwrap_or("");
        let bv = b.get("updated_at").and_then(|x| x.as_str()).unwrap_or("");
        bv.cmp(av)
    });
    items.truncate(limit);
    Json(json!({ "sessions": items })).into_response()
}

/// D3b: declarative runtime snapshot. The foundation for `feral export` /
/// `feral import` (a future phase — v1 is read-only). Locally-sourced keys are
/// filled; sidecar-sourced keys (connectors/memories/dreams) are `null` until
/// the sidecar-round-trip vertical wires them, so a client can tell the
/// difference between "empty" and "not yet available".
async fn runtime_manifest(State(state): State<ApiState>) -> impl IntoResponse {
    let rt = &state.runtime;
    let active_model = rt.manager.current().map(|m| m.name);
    let models: Vec<String> = models::scan_models_dir()
        .unwrap_or_default()
        .into_iter()
        .map(|m| m.id)
        .collect();
    Json(json!({
        "version": env!("CARGO_PKG_VERSION"),
        "models": models,
        "active_model": active_model,
        "agent_model": rt.active_agent_model.lock().clone(),
        "loras": { "active": crate::inference::active_lora_adapter() },
        "providers": {
            "backend": crate::inference::active_backend_label(),
            "gpu": crate::inference::gpu_active(),
        },
        "connectors": Value::Null,
        "memories": Value::Null,
        "dreams": Value::Null,
    }))
}

/// D3: unified observability stream. Subscribes to the runtime's broadcast bus
/// (fed by any `BroadcastEvents` sink) and replays every host event as SSE.
/// The headless gateway wires `BroadcastEvents`; on the desktop host today the
/// bus is idle (TauriEvents forwards to the webview) — uniform `/events` on
/// desktop is a Faza 5 concern. `curl -N /events` proves it live.
async fn runtime_events(
    State(state): State<ApiState>,
) -> Sse<impl Stream<Item = Result<Event, Infallible>>> {
    use async_stream::stream;
    let mut rx = state.runtime.events_tx.subscribe();
    let s = stream! {
        loop {
            match rx.recv().await {
                Ok(ev) => {
                    let data = json!({ "event": ev.event, "data": ev.payload }).to_string();
                    yield Ok::<_, Infallible>(Event::default().event("runtime").data(data));
                }
                // A subscriber that fell behind the 512-event ring lost `n`
                // events. Log it and keep streaming from the current tail
                // rather than tearing the connection down.
                Err(broadcast::error::RecvError::Lagged(n)) => {
                    tracing::warn!(skipped = n, "/events subscriber lagged");
                    continue;
                }
                Err(broadcast::error::RecvError::Closed) => break,
            }
        }
    };
    Sse::new(s)
}

async fn v1_chat_completions(
    State(state): State<ApiState>,
    Json(req): Json<ChatReq>,
) -> impl IntoResponse {
    if !wait_for_model(&state, &req.model).await {
        return no_model_response();
    }
    let mut params = params_from_options(req.options.as_ref());
    apply_max_tokens(&mut params, req.max_tokens);
    apply_grammar(&mut params, &req);
    apply_session(&mut params, &req);
    let model = req.model.clone();
    let stream = req.stream.unwrap_or(false);
    let messages = req.into_messages();
    if stream {
        sse_from_chat(state, model, messages, params, true).into_response()
    } else {
        let text = collect_chat(&state, messages, params).await;
        Json(json!({
            "id": format!("chatcmpl-{}", uuid::Uuid::new_v4()),
            "object": "chat.completion",
            "model": model,
            "choices": [{
                "index": 0,
                "message": { "role": "assistant", "content": text },
                "finish_reason": "stop",
            }],
        })).into_response()
    }
}

/// Apply the OpenAI-standard top-level `max_tokens` over whatever
/// `params_from_options` produced. A request that explicitly asks for fewer
/// tokens must win over the 1024-token default; `0` is ignored as a no-op.
fn apply_max_tokens(params: &mut InferParams, max_tokens: Option<u32>) {
    if let Some(mt) = max_tokens {
        if mt > 0 {
            params.max_tokens = mt;
        }
    }
}

/// Copy the Feral grammar extension fields from the request onto the inference
/// params. A no-op for standard OpenAI clients (both fields default to None).
fn apply_grammar(params: &mut InferParams, req: &ChatReq) {
    params.grammar = req.grammar.clone();
    params.grammar_triggers = req.grammar_triggers.clone();
}

/// P1 (prompt caching): copy the Feral session-id extension from the request
/// onto the inference params. Currently used for audit/logging only —
/// contexts come from the P6 pool with no session→context affinity yet. The
/// field is plumbed here so a future affinity strategy (or per-session
/// telemetry) can be added without another breaking schema change on the API.
fn apply_session(params: &mut InferParams, req: &ChatReq) {
    params.session_id = req.session_id.clone();
}

fn params_from_options(opts: Option<&Value>) -> InferParams {
    let mut p = InferParams::default();
    if let Some(o) = opts {
        if let Some(v) = o.get("temperature").and_then(|v| v.as_f64()) { p.temperature = v as f32; }
        if let Some(v) = o.get("top_p").and_then(|v| v.as_f64()) { p.top_p = v as f32; }
        if let Some(v) = o.get("repeat_penalty").and_then(|v| v.as_f64()) { p.repeat_penalty = v as f32; }
        if let Some(v) = o.get("num_predict").and_then(|v| v.as_u64()) { p.max_tokens = v as u32; }
    }
    p
}

async fn collect_chat(state: &ApiState, messages: Vec<Message>, params: InferParams) -> String {
    use futures::StreamExt;
    let stop = Arc::new(AtomicBool::new(false));
    let mut out = String::new();
    let mut stream = Box::pin(state.manager.stream_chat(messages, params, stop, None));
    while let Some(tok) = stream.next().await {
        match tok {
            Ok(t) => out.push_str(&t),
            Err(e) => { tracing::warn!("token error: {}", e); break; }
        }
    }
    out
}

fn sse_from_chat(
    state: ApiState,
    model: String,
    messages: Vec<Message>,
    params: InferParams,
    openai_format: bool,
) -> Sse<impl Stream<Item = Result<Event, Infallible>>> {
    use async_stream::stream;
    use futures::StreamExt;

    let s = stream! {
        let stop = Arc::new(AtomicBool::new(false));
        let mut chat = Box::pin(state.manager.stream_chat(messages, params, stop, None));
        while let Some(tok) = chat.next().await {
            let t = match tok { Ok(t) => t, Err(e) => { tracing::warn!("sse token error: {}", e); break; } };
            let payload = if openai_format {
                json!({
                    "id": "chatcmpl-stream",
                    "object": "chat.completion.chunk",
                    "model": model,
                    "choices": [{ "index": 0, "delta": { "content": t } }],
                })
            } else {
                json!({
                    "model": model,
                    "message": { "role": "assistant", "content": t },
                    "done": false,
                })
            };
            yield Ok::<_, Infallible>(Event::default().data(payload.to_string()));
        }
        let done = if openai_format {
            json!({
                "id": "chatcmpl-stream",
                "object": "chat.completion.chunk",
                "model": model,
                "choices": [{ "index": 0, "delta": {}, "finish_reason": "stop" }],
            })
        } else {
            json!({ "model": model, "done": true })
        };
        yield Ok(Event::default().data(done.to_string()));

        // OpenAI streaming protocol terminates with `data: [DONE]`. The
        // SSE parser waits for this sentinel — without it the stream is treated
        // as an incomplete terminal response.
        if openai_format {
            yield Ok(Event::default().data("[DONE]"));
        }
    };
    Sse::new(s)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::host::HostEvent;

    fn agent_output(line: &str) -> HostEvent {
        HostEvent { event: "feral://agent-output".into(), payload: json!({ "data": line }) }
    }

    #[test]
    fn parse_agent_output_extracts_chunk() {
        let ev = agent_output(r#"{"type":"chunk","id":"abc","content":"hel"}"#);
        assert_eq!(
            parse_agent_output(&ev),
            Some(AgentOutputLine {
                ty: "chunk".into(),
                id: "abc".into(),
                content: "hel".into(),
                raw: json!({"type":"chunk","id":"abc","content":"hel"}),
            })
        );
    }

    #[test]
    fn parse_agent_output_done_carries_full_text() {
        let ev = agent_output(r#"{"type":"done","id":"abc","content":"hello","stopped":false}"#);
        assert_eq!(
            parse_agent_output(&ev),
            Some(AgentOutputLine {
                ty: "done".into(),
                id: "abc".into(),
                content: "hello".into(),
                raw: json!({"type":"done","id":"abc","content":"hello","stopped":false}),
            })
        );
    }

    #[test]
    fn parse_agent_output_ignores_non_agent_events() {
        let ev = HostEvent { event: "feral://agent-ready".into(), payload: json!({}) };
        assert_eq!(parse_agent_output(&ev), None);
    }

    #[test]
    fn parse_agent_output_ignores_unparseable_data() {
        // A log line that isn't JSON must not crash the correlator.
        assert_eq!(parse_agent_output(&agent_output("not json")), None);
    }
}

// ── Phase 1 catalog handlers (2026-07-07) ──────────────────────────────────
//
// Both handlers attach the catalog-version header so a client built
// against an older shape can detect the mismatch and fall back to its
// bundled slice. The body shape mirrors the Rust types 1:1 — `Provider`
// enum serialises to lowercase via `#[serde(rename_all = "lowercase")]`
// (byok.rs:9), `PairingMethod` likewise. No server-side filtering:
// clients get the full catalog so they can layer their own query
// (search, "show only free tier", etc.) without a server round-trip.

/// `GET /runtime/providers/catalog` — returns the canonical provider
/// metadata. Header `X-Feral-Catalog-Version` carries the version
/// clients pin against.
///
/// `pub` so `tests/catalog_endpoints.rs` can mount just the catalog
/// routes on a fresh `axum::Router` without constructing the full
/// `ApiState`. The handler is stateless and idempotent; exposing it
/// doesn't widen the public API surface — the route is what's
/// reachable from the host's actual router.
pub async fn runtime_providers_catalog() -> Response {
    let body = byok::provider_catalog();
    catalog_response(byok::CATALOG_VERSION, body)
}

/// `GET /runtime/connectors/catalog` — returns the canonical connector
/// metadata. Same header policy as `/runtime/providers/catalog`. `pub`
/// for the same reason as `runtime_providers_catalog`.
pub async fn runtime_connectors_catalog() -> Response {
    let body = connector_catalog::connectors_catalog();
    catalog_response(connector_catalog::CONNECTORS_CATALOG_VERSION, body)
}

/// Common response shape for both catalog endpoints. The header carries
/// the catalog version; clients compare it to their own build-time pin
/// and treat a mismatch as a drift signal — never silently drop
/// providers.
fn catalog_response<T: serde::Serialize>(version: u32, body: Vec<T>) -> Response {
    let mut headers = HeaderMap::new();
    let v = version.to_string();
    // `X-Feral-Catalog-Version: <int>`. The header name is a static
    // ASCII string (compile-time constant), so `from_static` is
    // infallible in this `http` crate version. The value carries the
    // version number, which is ASCII digits and therefore also
    // infallible in practice — but we degrade gracefully if the value
    // happens to be malformed (it never will be).
    let name = HeaderName::from_static("x-feral-catalog-version");
    if let Ok(value) = HeaderValue::from_str(&v) {
        headers.insert(name, value);
    }
    (headers, Json(body)).into_response()
}
